### ISSUE TITLE
How to support Kafka (Java) LongDeserializer ?

### ISSUE THREAD

**Issue by angelozerr** [tulios/kafkajs#1038]
I'm sorry if it's an invalid issue but I'm neebie with kafkajs.

Kafka (in Java) provides several serializer/deserializer. For instance it provides [LongDeserializer](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/serialization/LongDeserializer.java)

I tried to consume the avro `LongType` from https://github.com/mtth/avsc/blob/10225a0f2fd026f1a553e832875f4173764486a4/lib/utils.js#L524 but the result is not the expected value.

I think it's because it's an avro type. That's why I create the issue here and I wonder if kafkajs could provide the same serializer/deserializer than kafka?

**Comment by Nevon** [comment]
This is outside of the scope of KafkaJS, as it's an issue of encoding/decoding of your actual message data. Since we pass the messages straight to the consumer, it's trivial to insert what they in the Java world would call a deserializer:

```js
{
  eachMessage: deserializer(eachMessageHandler)
}
```

Where deserializer just intercepts the messages, deserializes them and provides them to your "eachMessageHandler". In fact, if you're using the confluent schema registry, we already provide a library that does this for you: https://www.npmjs.com/package/@kafkajs/confluent-schema-registry

In terms of your specific problem with longs, that falls in the scope of `avsc`. They have a wiki article on how to use a custom long type there: https://github.com/mtth/avsc/wiki/Advanced-usage#custom-long-types

**Comment by angelozerr** [comment]
Thanks so much for your feedback @Nevon To be honnest with you, I did like you suggested and I'm happy that you confirm that I'm in the right direction.

My problem is that when I produce in Java context a message with Java standard [org.apache.kafka.commons.serialization.LongDeserializer](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/serialization/LongDeserializer.java) it seems it doesn't exist a deserializer in node context. 

If I understand correctly,I must implement my own `org.apache.kafka.commons.serialization.LongDeserializer` in JS. As it's a Kafka standard serializer, I wonder why kafkajs could not host it?

**Comment by Nevon** [comment]
> As it's a Kafka standard serializer, I wonder why kafkajs could not host it?

Because we don't look inside your messages. Notice how in our messages, the values are of type `Buffer`. That is, to us, they are just bytes and we don't know anything about how to interpret them. We don't know if it's a stringified JSON object from Javascript, a serialized class from Java, a Protobuf encoded message, an Avro record or anything else. Only the message producer can know what the message is and how to deserialize it.

The Java serializer is just one possible serialization scheme out of many. Also note that it has nothing to do with Avro. It's just a Java specific way of serializing.

In your case, there's not much to implement. Node's buffer class already comes with a way to read 64 bit integers. Let's take an example:

```java
import java.util.Arrays;

class Main {  
  public static void main(String args[]) {
    long num = 123456789;
    byte[] serialized = Main.serialize(num);

    System.out.println(Arrays.toString(serialized)); 
  }

  private static byte[] serialize(Long data) {
        if (data == null)
            return null;

        return new byte[] {
            (byte) (data >>> 56),
            (byte) (data >>> 48),
            (byte) (data >>> 40),
            (byte) (data >>> 32),
            (byte) (data >>> 24),
            (byte) (data >>> 16),
            (byte) (data >>> 8),
            data.byteValue()
        };
    }
}
```

If I run that in Java, I get `[0, 0, 0, 0, 7, 91, -51, 21]`.

Now we simply read that in Node:

```js
> Buffer.from([0, 0, 0, 0, 7, 91, -51, 21]).readBigInt64BE();
123456789n
```

As you can see, we get the same number back.

Maybe what tripped you up was that in Avro numbers are encoded as little endian, as the example I linked to shows, but the Java long serializer is using big endian.

**Comment by angelozerr** [comment]
Thanks so much @Nevon for your great explanation!

It's not finished, but I have started to implement Java Kafka serializer in nodejs in https://github.com/jlandersen/vscode-kafka/blob/e4fdf041277a77abae7f3c5d3724ab103bf73f27/src/client/serialization.ts
