### ISSUE TITLE
How to consume from specific partition of a kafka topic by using KafkaJS library

### ISSUE THREAD

**Issue by Sieusaosieungo** [tulios/kafkajs#1060]

**Comment by Nevon** [comment]
KafkaJS uses automatic partition assignment, rather than manual assignment, which means that members of the consumer group will be assigned partitions automatically according to the whims of the partition assigner. This is unlike some other clients where each consumer instance manually subscribes to individual partitions.

You _can_ implement your own partition assigner to further control this behavior, but fully manual partition assignment is not something we support. https://kafka.js.org/docs/consuming#a-name-custom-partition-assigner-a-custom-partition-assigner
