### ISSUE TITLE
Subscribe on regexp not working as expected

### ISSUE THREAD

**Issue by Mamoru1234** [tulios/kafkajs#1086]
**Describe the bug**
New topic which match the pattern is not received after rebalance.
**To Reproduce**
I have created [sample project which describe the problem](https://github.com/Mamoru1234/kafka-js-issue/tree/subscribe_to_pattern). 

**Expected behavior**
I expect that new consumer call subscribe and after rebalance new topic should be handled properly.

**Observed behavior**
Despite the fact that new consumer call subscribe for new topic this topic is not assigned to any consumer in group.

**Environment:**
 - KafkaJS version [1.15.0]

**Additional context**
You can setup needed env from compose file in compose directory.

**Comment by Nevon** [comment]
[As per the documentation](https://kafka.js.org/docs/consuming):

> The consumer will not match topics created after the subscription. If your broker has topic-A and topic-B, you subscribe to /topic-.*/, then topic-C is created, your consumer would not be automatically subscribed to topic-C.

In your test, you are essentially subscribing to a different set of topics in your two consumers. Consumer 1 is subscribing to `test_1` and Consumer 2 is subscribing to `test_1` and `test_2`. If consumer 1 receives an assignment for `test_2`, which it is not subscribed to, it will discard that and emit a warning.

**Comment by Mamoru1234** [comment]
Actually in docs there is no mention about that. consumer 2 tries to subscribe why consumer 1 discard this new topic? As far as I am aware same scenario works with java client. What is the reasoning behind discarding new assignment?

**Comment by Nevon** [comment]
I don't know what the Java client does, but the way that KafkaJS works is that the regex subscription is that it just lists all topics and subscribes to the ones that match the regex. It's not really any different from subscribing with a regular string topic, except you don't have to list all of them manually.

The reasoning behind discarding assignments that don't match the topics you are subscribed to is because the assumption is that a consumer should never receive assignments for topics they aren't subscribed to. For example, let's say you have application version 1 which is subscribed to the `purchases` topic and processing `purchase` events. Then you deploy application version 2, which now subscribes to both `purchases` and `refunds`. During a rolling deployment, you may have application version 1 and version 2 running at the same time. Unless we discard assignments for unsubscribe topics, suddenly application version 1 will start to receive events from the `refunds` topic, which it has no idea what to do with.

You would have to handle that in your application logic then, so that you refuse to process any messages for topics you don't expect to receive messages for, and also you'd need to make sure not to commit those offsets for partitions in that topic, since otherwise those messages would be skipped.

Instead, we handle this internally. We don't fetch messages for topics we're not subscribed to, so there's no risk that your application receives messages it doesn't know how to handle.
