### ISSUE TITLE
Would you consider support for MSK & IAM integration

### ISSUE THREAD

**Issue by robertbarron** [tulios/kafkajs#1098]
**Is your feature request related to a problem? Please describe.**
Recently, AWS released an integration between Amazon MSK (Amazon Managed Stream for Kafka) and IAM (Identity & Access Management). There is an example of this [implementation](https://aws.amazon.com/blogs/big-data/securing-apache-kafka-is-easy-and-familiar-with-iam-access-control-for-amazon-msk/) but they're using a java client and a library named [aws-msk-iam-auth](https://github.com/aws/aws-msk-iam-auth) in order to match IAM security.

**Describe the solution you'd like**
Would like to fully support this new integration.

**Additional context**
Currently, the only security measures that can be added to a Amazon MSK cluster is by protecting it with security groups or TLS. These options are full deny or full allow, there's no way to define a set of access per topic. This new integration with IAM allow this.

**Comment by Nevon** [comment]
Currently the SASL mechanisms are all bundled into KafkaJS, so while I would like for is to support this, the first would need to be to allow for pluggable mechanisms so that we don't have to bundle the AWS-SDK into KafkaJS. Similar to what we do with compression codecs. I opened up an issue for this about a year back: #840

Since the server side implementation is closed-source, properly testing this in CI is gonna be a mess. Either we fall back to just unit testing or we have to provision an MSK cluster during test runs, which we don't really have the funds for (nor time to implement). Yet another reason for this to live outside of KafkaJS core.

**Comment by jmaver-plume** [comment]
@Nevon If I understand this issue correctly, this package does not currently support MSK & IAM integration, right?

**Comment by Nevon** [comment]
That is correct.

**Comment by jmaver-plume** [comment]
@Nevon I see you already started with supporting this feature: https://github.com/aws/aws-msk-iam-auth/issues/10#issuecomment-846599054
We would like to help in developing this. Is this pushed to any branch?

**Comment by Nevon** [comment]
No, I was developing it outside of KafkaJS, and never pushed the repo. It was in a very early stage anyway, so not much to continue on. Like I mentioned in my earlier comment, we would not want to bundle this into KafkaJS itself, but rather keep it as a plugin, so that we don't end up bringing in big dependencies that are useless for 99% of users, and making the KafkaJS testing process far more complicated since the authentication mechanism is proprietary and we can't even use it in a local Kafka cluster. That's one of the reasons I wrote #840, so that these things could be injected as plugins instead of having to bundle everything into KafkaJS.

So feel free to take a stab at it, using the branch in #840 as a peer dependency. I know I ran into some rough spots around the Typescript interface, where it was difficult to export an interface that allowed the authentication mechanism to integrate in a type safe way, so probably there will need to be some tweaking there as well to make it work well - but it does _work_, even if the interface needs some more love.

**Comment by jmaver-plume** [comment]
@Nevon I created some demo of configuration here: https://github.com/jmaver-plume/kafka-msk-iam-demo
With example you list topics to validate we have permissions.

**Comment by kasunbdn** [comment]
hi @jmaver-plume , I tested your example with MSK serverless version. I couldn't receive messages from the consumers. But create tpoics, send messages works fine.  when I point the same code to a non-serverless version of MSK, everything works fine. Do you have any idea what has gone wrong?

**Comment by donske07** [comment]
I'm currently trying to integrate with aws serverless and running into the same issue. It seems I can do everything except consume messages. The application hangs on JoinGroup request.

**Comment by Nevon** [comment]
Injecting custom authentication mechanisms is now available in a beta release. See https://github.com/tulios/kafkajs/issues/840#issuecomment-1177251826 for more information.

**Comment by NikolayPIvanov** [comment]
https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism This example is not working with the beta release when using Mechanism as authenticationProvider.
The error is KafkaJSProtocolError: [<some id>]: Access denied

**Comment by bitnitesh** [comment]
@Nevon Do we have working example to connect to AWS MSK Cluster using kafkajs library,i tried using https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism but not able to connect and getting below error.

/home/ubuntu/ext-drive/sampleProject/msk-iam-demo/kafka.js:3
AuthenticationMechanisms[Type] = () => Mechanism
                               ^

TypeError: Cannot set property 'AWS_MSK_IAM' of undefined
    at Object.<anonymous> (/home/ubuntu/ext-drive/sampleProject/msk-iam-demo/kafka.js:3:32)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/ubuntu/ext-drive/sampleProject/msk-iam-demo/server.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)


It would be really helpful to provide any specific version of node.js is required to execute the server.js file.

**Comment by jmaver-plume** [comment]
@NikolayPIvanov @bitnitesh I updated the library to work the new interface provided by #840.
https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism/tree/v2.0.1

**Comment by bitnitesh** [comment]
> @bitnitesh I have verified that the library works using https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism/blob/main/example/cloudformation.yaml. Is your MSK correctly provisioned for IAM? Library is using https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_node.html to get `accessKeyId` and `sessionToken`.

@jmaver-plume Yes for MSK clsuter  IAM role-based authentication is Enabled

**Comment by Nevon** [comment]
Closing this issue, as KafkaJS now provides the capability to inject custom authentication mechanisms. Discussions about specific plugins should be had within those issue trackers.
