### ISSUE TITLE
Header value cannot be a number

### ISSUE THREAD

**Issue by Naorik** [tulios/kafkajs#1124]
```
export interface IHeaders {
  [key: string]: Buffer | string | undefined
}
```

Why can't I use number as a header's value?

**Comment by Nevon** [comment]
Because in the Kafka protocol, a header value is just a byte array. In Node we would use a Buffer to represent that. In KafkaJS, we toss the header value into [`Buffer.from` ](https://nodejs.org/api/buffer.html#buffer_static_method_buffer_from_buffer), which only supports creating a Buffer from another Buffer or a string (technically also from an array, but that would just allocate an empty buffer, so not very useful in this case).

If you want to send a number value, you have to define how you want it represented as a byte array. For example, how big is it and is it big-endian or little-endian. Buffer already has built-in methods to do this, for example:

```js
// Allocate a 4 byte buffer and write a signed 32-bit big-endian integer into it
const int = Buffer.alloc(4).writeInt32BE(-1234568)

// Allocate 8 bytes and write a double-precision float into it
const double = Buffer.alloc(8).writeDoubleBE(3.14159, 0)
```
