### ISSUE TITLE
make resolveOffset return an indicator when all messages of the batch are resolved

### ISSUE THREAD

**Issue by backbone87** [tulios/kafkajs#1125]
**Is your feature request related to a problem? Please describe.**
When processing a batch you can use `resolveOffset` to mark a message as done. I would like to know if the batch that contains the message has all its offsets resolved. Currently, I wrap the resolveOffset and reduce a set of offset and return the remaining offset count. I also know that one could use uncommitedOffsets, but since this does a lot of copying around and also returns uncommittedOffsets of all partitions, it is neither performant to be checked on each resolveOffset nor a nice DX.

**Describe the solution you'd like**
`resolveOffset` returns either a boolean that is `true` when all messages of the current batch are resolved, or it returns a number with how many messages are not yet resolved in the batch.

**Comment by Nevon** [comment]
Could you elaborate a bit on your use-case? Perhaps showing some pseudo-code of what you want to achieve? I don't think I really understand what the problem you're trying to solve is.

Resolving an offset is literally just setting a single number value in a map. Essentially `resolvedOffsets[partition] = offset`. So it's just a pointer to where in the partition you are. There's no data structure that holds information about each individual offset, like:

```js
resolvedOffsets = {
  [partition]: {
    '1': true,
    '2': true,
    '3': false,
    '4': false
  }
}
```

So finding out how many messages are remaining in a batch would be something like: `batch.messages.filter(({ offset }) => offset > lastResolvedOffset).length`. Of course if you're processing the messages in order, it's just the length of the batch minus the current message index:

```js
for (let i = 0; i < batch.messages.length; i++) {
  const message = batch.messages[i];
  await processMessage(message);
  const remaining = batch.messages.length - i;
}
```

**Comment by Nevon** [comment]
> from your description i got the impression that resolveOffset can not deal with out of order processing, because if it happens to be that the last message in a batch was completely processed first then resolveOffset will basically mark the whole batch as resolved and there committable on the next auto commit cycle?

Yes, that's exactly right. Or if you first resolve offset 100 and then later resolve offset 50, you'd end up reprocessing any offset >50.

You can take a look at this method, which is how the `eachMessage` interface works, which is essentially just a straightforward implementation of `eachBatch` under the hood: https://github.com/tulios/kafkajs/blob/f8366f30d965214701393b31e1cc6eddae1fe9db/src/consumer/runner.js#L142-L172

In this case we're processing the offsets in order, which is why we can resolve each message offset after processing it. If you're processing several messages in the same batch in parallel, you'll need to keep track of the resolved offsets yourself and only _actually_ resolve an offset if all the previous offsets have also been resolved.

Or you can wait until you've processed all messages in the batch and resolve `batch.lastOffset()` instead, but then if something goes wrong in the middle of a batch, you'll have to reprocess the whole batch instead of just the unresolved ones.

**Comment by backbone87** [comment]
thank you for the explanations. i think using the example from above to track individual message processing and then completing the batch should be enough when using the `eachBatchAutoResolve` option. reprocessing a batch or parts of a batch is no big deal in our case, we just need "at least once" behavior.

i wonder if this is something that would be a candidate for an extension of kafkajs. if not just close this issue
