### ISSUE TITLE
How to download the next batch while processing the current batch

### ISSUE THREAD

**Issue by stavalfi** [tulios/kafkajs#1211]
My producer produce messages in a specific order. To preserve this specific order while consuming, we have single partition and a single consumer. 

For performance reasons, I'm consuming batches and `maxBytesPerPartition = 1024 * 1024 * 50`

I'm seeing a `delay` of couple of seconds between batch ends to process until the next one is starting to be processed.

## My Request

KafkaJs should download the next batch while my app is processing the current batch. 

### Why

The processing time of a batch takes 0.5s, while the download of the batch takes much longer (couple of seconds).

**Comment by Nevon** [comment]
We cannot download a new batch while you are processing the current batch, because we won't know what offset to fetch from until you are done processing the current batch.

The delay you are seeing is possibly due to the configuration of [`minBytes`, `maxBytes`, `maxBytesPerPartition` and `minWaitTimeInMs`](https://kafka.js.org/docs/consuming#a-name-options-a-options), which control whether you want to prioritize throughput or latency.

If you want to improve performance, the way to do that is to have multiple partitions and consumers, and key your messages by your aggregation key. Unless you need global ordering between all messages in the system, which is usually not the case. If you do need global ordering, you don't have a way to scale.
