### ISSUE TITLE
Support Kafka 3.0

### ISSUE THREAD

**Issue by ryan65** [tulios/kafkajs#1214]
Hi 
I would like to know if there have been plans for a new release that will support Kafka 3.0
Thanks.

**Comment by ashercoren** [comment]
Can we please get an answer here? Does this library support Kafka 3.0?

**Comment by Nevon** [comment]
What issues have you ran into running KafkaJS against Kafka 3.0? As far as I'm aware, it's all backwards compatible changes.

**Comment by ashercoren** [comment]
We haven't yet tried running KafkaJS against Kafka 3.0, because we are afraid of what may brake...
Looking at the [change log](https://kafka.apache.org/documentation/#upgrade_300_notable), there are some potentially breaking changes, for example:
* The Streams API removed all deprecated APIs that were deprecated in version 2.5.0 or earlier
* Kafka Streams no longer has a compile time dependency on "connect:json" module
* A number of deprecated classes, methods and tools have been removed

**Comment by Nevon** [comment]
Kafka Streams is a library built on top of the Java Kafka client, so changes to that has nothing to do with KafkaJS. Same with all the changes to the Java Kafka client.

The only thing that matters for us is if anything has changed in the protocol to break backwards compatibility, which basically never happens because it would mean that also older versions of the Java Kafka client would stop working. It's a bit like how Chrome releasing a new version doesn't mean that Firefox stops working - it's just that it might not support all new features of the web. You could try upgrading the Kafka image we use in our tests to 3.0 and run the tests to see if anything has broken.

**Comment by ryan65** [comment]
> Kafka Streams is a library built on top of the Java Kafka client, so changes to that has nothing to do with KafkaJS. Same with all the changes to the Java Kafka client.
> 
> The only thing that matters for us is if anything has changed in the protocol to break backwards compatibility, which basically never happens because it would mean that also older versions of the Java Kafka client would stop working. It's a bit like how Chrome releasing a new version doesn't mean that Firefox stops working - it's just that it might not support all new features of the web. You could try upgrading the Kafka image we use in our tests to 3.0 and run the tests to see if anything has broken.

Thanks Nevon
So from what I understand you guess is that it should be Ok assuming we dont use new features.
Just one question , regarding the maintenance status of this library, because I noticed that there have been no updates for more than one year. Are any updates expected sometime ?

**Comment by Nevon** [comment]
> Just one question , regarding the maintenance status of this library, because I noticed that there have been no updates for more than one year. Are any updates expected sometime ?

Last update was 11 days ago, so changes still trickle in and those are published [here](https://www.npmjs.com/package/kafkajs/v/beta). But development has definitely slowed down since neither me nor Tulio are actively working with Kafka anymore, and neither of our workplaces are sponsoring us to work on KafkaJS at the moment, so it's pretty much just me in my spare time.
