### ISSUE TITLE
Repeated consumer problem

### ISSUE THREAD

**Issue by Ding9257** [tulios/kafkajs#1232]
- code
![kafkajs-config](https://user-images.githubusercontent.com/18475569/142596611-82e38d94-47d8-4f1d-8990-80bc88d7e64b.png)
![kafkajs-code](https://user-images.githubusercontent.com/18475569/142596631-0a0bf278-1afb-4ac9-82de-289832f715b3.png)

- log
![kafkajs-result](https://user-images.githubusercontent.com/18475569/142596692-871207d9-5c16-4a40-a602-cd04347678bb.png)

- why

**Comment by sateffen** [comment]
I guess you found the mistake already, but just for completeness:

You have a typo in calculating the new offset. You used a `*` instead of `+`, so you wrote `offset: message.offset * 1` instead of `offset: message.offset + 1`. Because of that you commit the same offset over and over, and keep reading the same message over and over, not making progress.

I think with that, this issue could be closed.
