### ISSUE TITLE
I am facing this issue when i try to connect to remote server, Please help on the below error

### ISSUE THREAD

**Issue by ShivakumarRathod** [tulios/kafkajs#1243]
KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionError: Connection error: getaddrinfo ENOTFOUND ip.internal
    at Socket.onError (C:\QUYTECH_PROJECTS\football_node\node_modules\kafkajs\src\network\connection.js:152:23)
    at Socket.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  name: 'KafkaJSNumberOfRetriesExceeded',
  retriable: false,
  helpUrl: undefined,
  originalError: KafkaJSConnectionError: Connection error: getaddrinfo ENOTFOUND ip.internal
      at Socket.onError (C:\QUYTECH_PROJECTS\football_node\node_modules\kafkajs\src\network\connection.js:152:23)
      at Socket.emit (events.js:375:28)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    retriable: true,
    helpUrl: undefined,
    broker: 'ip.internal:9092',
    code: 'ENOTFOUND'
  },
  retryCount: 5,
  retryTime: 9114
}

**Comment by OneCricketeer** [comment]
Have you verified that `ip.internal` does not have a firewall and that port 9092 is the correct port that is externally listening for Kafka? By default, Kafka does not expose external ports

**Comment by Nevon** [comment]
Closing this as inactive, and clearly a misconfiguration rather than an issue in KafkaJS.

**Comment by nikitkhakholia** [comment]
{"level":"ERROR","timestamp":"2023-02-01T06:45:55.008Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:55.027Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:55.092Z","logger":"kafkajs","message":"[Producer] Failed to send messages: Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","retryCount":0,"retryTime":290}
{"level":"ERROR","timestamp":"2023-02-01T06:45:55.095Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:55.472Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:55.482Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:55.489Z","logger":"kafkajs","message":"[Producer] Failed to send messages: Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","retryCount":1,"retryTime":586}
{"level":"ERROR","timestamp":"2023-02-01T06:45:55.492Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:56.090Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:56.093Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:56.100Z","logger":"kafkajs","message":"[Producer] Failed to send messages: Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","retryCount":2,"retryTime":1010}
{"level":"ERROR","timestamp":"2023-02-01T06:45:56.105Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:57.128Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:57.131Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:57.137Z","logger":"kafkajs","message":"[Producer] Failed to send messages: Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","retryCount":3,"retryTime":2262}
{"level":"ERROR","timestamp":"2023-02-01T06:45:57.139Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:59.455Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:59.457Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:45:59.464Z","logger":"kafkajs","message":"[Producer] Failed to send messages: Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","retryCount":4,"retryTime":5136}
{"level":"ERROR","timestamp":"2023-02-01T06:45:59.466Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:46:04.660Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:46:04.668Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2023-02-01T06:46:04.678Z","logger":"kafkajs","message":"[Producer] Failed to send messages: Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","retryCount":5,"retryTime":8700}
{"level":"ERROR","timestamp":"2023-02-01T06:46:04.681Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain","broker":"DESKTOP-CER0N21.localdomain:9092","clientId":"bets-api","stack":"Error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionError: Connection error: getaddrinfo ENOTFOUND DESKTOP-CER0N21.localdomain
    at Socket.onError (D:\DexWin\basketball-bets-api\node_modules\kafkajs\src\network\connection.js:210:23)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  name: 'KafkaJSNumberOfRetriesExceeded',
  retriable: false,
  helpUrl: undefined,
  retryCount: 5,
  retryTime: 8700
}






This happens when i try to connect kafka hosted at ubuntu on WSL. Tried turning off ipv6 but doesnot help

**Comment by mdsiyad** [comment]
facing same issue

**Comment by mjalloul08** [comment]
the same  "Connection error: read ECONNRESET KafkaJSNonRetriableError"
