### ISSUE TITLE
Single transaction producer for all messages vs dedicated transaction producer instances for each message

### ISSUE THREAD

**Issue by sureshballa** [tulios/kafkajs#1282]
Would like to check on best practices. Have a single transactional producer to produce all messages or should we spin up a new instance of transactional producer for each message produce request? If we are suggesting single, should we call connect before producing every message and disconnect after a successful message is produced?

The reason why I am asking this request is - we are using a single instance of transactional producer and if we encounter KafkaJSNonRetriableError: Transaction state exception (), then for one message, then all sub sequent message produce request is not happening - like blocking every message produce opeation.

```
{"stack":"KafkaJSNonRetriableError: Transaction state exception: Cannot call \"beginTransaction\" in state \"ABORTING\"\n    at Object.beginTransaction (/app/node_modules/kafkajs/src/producer/eosManager/transactionStateMachine.js:25:23)\n    at Object.transaction (/app/node_modules/kafkajs/src/producer/index.js:144:29)\n    at DomainProducerMessagingRepositoryKafkaJS.<anonymous> (/app/node_modules/***/shared-kernel/dist/infrastructure/messaging/domain_producer_messaging_repository_kafkajs.js:252:61)\n    at step (/app/node_modules/***/shared-kernel/dist/infrastructure/messaging/domain_producer_messaging_repository_kafkajs.js:50:23)\n    at Object.next (/app/node_modules/***/shared-kernel/dist/infrastructure/messaging/domain_producer_messaging_repository_kafkajs.js:31:53)\n    at fulfilled (/app/node_modules/***/shared-kernel/dist/infrastructure/messaging/domain_producer_messaging_repository_kafkajs.js:22:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","message":"Transaction state exception: Cannot call \"beginTransaction\" in state \"ABORTING\"","name":"KafkaJSNonRetriableError","retriable":false}
```

**Environment:**
 - OS: docker
 - KafkaJS version 1.15
 - Kafka version 2.6.1
 - NodeJS version 14

**Comment by Nevon** [comment]
Usually you'd have one producer, but you can only have one transaction in process at any given time per producer. If you have multiple independent transactions, then they would each need their own producer.

The error you're receiving is telling you that you are trying to create a new transaction while in the process of aborting the currently ongoing transaction. Since there can only be one transaction ongoing per producer at any given time, you get an error. To avoid this, make sure you `await transaction.abort()` and `await transaction.commit()` before trying to create a new transaction.

**Comment by kamok** [comment]
@Nevon

We currently do use `await transaction`.

However, during that time, another request came into my REST Service and we handled that asynchronously (webhook handlers) and it began another transaction.

Is this saying that we need to use something like https://www.npmjs.com/package/async-lock library to ensure that only a single transaction can be created at a time? That the bit of code that handles said webhook can only start the next one once the previous one is processed?

**Comment by Nevon** [comment]
Yes, exactly. #1250 proposes that `producer.transaction()` waits to resolve until there are no other transactions ongoing, similar to how the [Java client's `initTransaction`](https://kafka.apache.org/23/javadoc/org/apache/kafka/clients/producer/KafkaProducer.html#initTransactions--) works, but currently you'll need to add that locking yourself.

But if you're producing from a webhook handler, rather than an input topic, you could have a pool of producers (just make sure they have different `transactionalId`) so that you can handle more than one request at a time.

**Comment by sureshballa** [comment]
Hi @Nevon , does this mean we have to wait till the feature #1250 is worked up. This is our basic requirement that we will have many requests to produce messages (via REST apis) and looks like there is no other solution than probably just using non-transational producer?

**Comment by jishnu-purath** [comment]
@Nevon Do you have any example on how the pool will work. We are currently using a producer pool and facing concurrency issues. 

This is how it looks like, 
```
export class ProducerPool {
    private producers: Producer[];

    private size: number;

    constructor(private limit: number) {
        this.producers = new Array(limit);
        this.size = 0;
    }

    public async obtain(): Promise<Producer> {
        let producer: Producer;
        if (this.size > 0) {
            this.size--;
            producer = this.producers[this.size];
            this.producers[this.size] = null as any;
        } else {
            producer = this.getNew();
            await producer.connect();
        }
        return producer;
    }

    public async recycle(producer: Producer): Promise<void> {
        if (this.size < this.limit) {            
            this.producers[this.size] = producer;
            this.size++;
        } else {
            await producer.disconnect();
        }
    }
    
    private getNew(): Producer {
    // Initialize new Producer here
    }
}
```

And to produce message from rest api 

```
const producer = await this.producerPool.obtain();
try {
  transaction = await this._producer.transaction();
  await transaction.send({
      topic,
      messages,
  });
  await transaction.commit();
} catch (error) {
    if (transaction) await transaction.abort();
    console.error(err);
    throw error;
} finally {
   await this.producerPool.recycle();
}

```

But when I use this I am getting a different error. 

```
The producer attempted to update a transaction while another concurrent operation on the same transaction was ongoing
```

**Comment by Nevon** [comment]
@sureshballa If you don't need a transactional producer, then there's no point in using one, so that's obviously the best solution. If you do need a transactional producer, then you will need to manage access to the producers yourself, like @kamok suggested with a lock.

@jishnu-purath: I would recommend reading through [this](https://www.confluent.io/blog/transactions-apache-kafka/) if you haven't already. You don't show it in your code, but I'm guessing you're using the same `transactionalId` for all the producers, which means that all except one will be fenced out.

**Comment by sureshballa** [comment]
Hi @Nevon , yes we don't want to compromise on EOS. Sure, will try async lock. Also, lets us know when we can expect #1250 to be released, something like this as out of box feature would be more beneficial for us.

**Comment by Nevon** [comment]
Closing this in favor of #1250. It'll get done when someone decides to take the time to develop it, I can't say when that'll be. I personally don't have any immediate plans to prioritize it.

**Comment by sureshballa** [comment]
Thanks, @Nevon
