### ISSUE TITLE
SASL Type Error

### ISSUE THREAD

**Issue by luizgribeiro** [tulios/kafkajs#1314]
**Describe the bug**
While using TypeScript, an error was provided by ts-server, informing that `plain` can't be used as `mechanism` for SALS.
This is probably a problem with the type definition for SASL.

**To Reproduce**

[This repo](https://github.com/luizgribeiro/kafka-bbb-poc) contains the code that I am working on and that resulted on this problem. Cloning it and following the README should lead to the same bug.
The error provided is the following:

![image](https://user-images.githubusercontent.com/10711482/158089083-35f129aa-2ae5-4c86-a260-7c85236934ff.png)

**Expected behavior**
It should be possible to use the value 'plain' as 'mechanism' for Kafka configuration.

**Observed behavior**
The TypeScript server cannot compile the code when the string 'plain' is being used as mechanism.

**Environment:**
 - OS: [Linux 5.13.19-2]
 - NodeJS version [16.8.0]
 - TypeScript version [4.6.2]

**Additional context**
The problem has probably been reported before [on this issue](https://github.com/tulios/kafkajs/issues/1236) but it was not properly fixed because it became inactive.

I've had some time to dig deeper and found that the problem lies on the `SASLOptions` type. The code bellow is probably the part that is causing trouble.

```typescript
type SASLMechanismOptionsMap = {
   plain: { username: string; password: string };
   "scram-sha-256": { username: string; password: string };                               
   "scram-sha-512": { username: string; password: string };                               
   aws: {                                                                                 
     authorizationIdentity: string;                                                       
     accessKeyId: string;                                                                 
     secretAccessKey: string;                                                             
     sessionToken?: string;                                                               
   };                                                                                     
   oauthbearer: {                                                                         
   oauthBearerProvider: () => Promise<OauthbearerProviderResponse>;
   };                                                                    
 };  
 export type SASLMechanism = keyof SASLMechanismOptionsMap;
 type SASLMechanismOptions<T> = T extends SASLMechanism
   ? { mechanism: T } & SASLMechanismOptionsMap[T]
   : never;
   export type SASLOptions = SASLMechanismOptions<SASLMechanism>;
```
The problem here is that SASLOption gets SASLMechanismOptions using SASLMechanism as it's generic type (last line). When 'plain' is provided as 'mechanism', it's type is 'string', which results in this error.
This hypothesis is confirmed by using Literal types for mechanism, that make it work as expected, like in the code bellow.

```typescript
       const mechanism: "plain" = "plain";                                                     
       const sasl = {
         username: env.KAFKA_KEY,
         password: env.KAFKA_SECRET,  
         mechanism: mechanism,              
       };
```

**Comment by Nevon** [comment]
If I understand the issue correctly, this is intentional behavior. The type of `mechanism` is a string literal union - meaning we only accept these specific values. Otherwise you could pass whatever string in there and it'd fail at runtime. If you pass a string, that's a wider type that isn't guaranteed at build-time to be one of the accepted values.

In your example code, the type of `sasl` is going to be:

```ts
{
  username: string;
  password: string;
  mechanism: string;
}
```

That's not the same thing as `SASLOptions`. If you tell the compiler that `sasl` is a `SASLOptions`, it'll work:

```ts
const sasl: SASLOptions = {
         username: env.KAFKA_KEY,
         password: env.KAFKA_SECRET,  
         mechanism: 'plain',
};
```

As a benefit, it'll also tell you if you messed up:

![Screenshot 2022-03-14 at 14 53 48](https://user-images.githubusercontent.com/83586/158186281-8997b519-ef31-4fa7-a829-f4d2ed503612.png)

**Comment by luizgribeiro** [comment]
Thanks @Nevon!

I'll use it with it's proper type declaration then. 

Do you think there's another way of implementing these types to make the compiler infer SASL type's without explicitly declaring it? 

I'm asking this because I couldn'f find any example of this case and, at the same time had to spend some time to make it work.
If it can be easier, I'd be glad to help and send a PR.

**Comment by Nevon** [comment]
With the way Typescript works currently, I don't believe so. To be clear, the compiler checking forcing you to verify that the value you're providing is actually a member of the desired type is a good thing. If we changed it so that the mechanism was just a string you wouldn't get a compile time warning, and instead the code would crash at runtime if you provided an invalid mechanism. What you're after is some kind of automatic narrowing based on the context, so that you don't have to tell the compiler that this string is actually not just a random string, but actually a member of a specific string literal union. There is a proposal for something like this here: https://github.com/microsoft/TypeScript/issues/16896

**Comment by luizgribeiro** [comment]
> With the way Typescript works currently, I don't believe so. To be clear, the compiler checking forcing you to verify that the value you're providing is actually a member of the desired type is a good thing. If we changed it so that the mechanism was just a string you wouldn't get a compile time warning, and instead the code would crash at runtime if you provided an invalid mechanism. What you're after is some kind of automatic narrowing based on the context, so that you don't have to tell the compiler that this string is actually not just a random string, but actually a member of a specific string literal union. There is a proposal for something like this here: [microsoft/TypeScript#16896](https://github.com/microsoft/TypeScript/issues/16896)

Thanks for clarifying. That is exactly it. I've seen this before on other languages and thought that it could be possible on Typescript as well.
