### ISSUE TITLE
The coordinator is not aware of this member errors or [Connection] Response Heartbeat(key: 12, version: 3) errors

### ISSUE THREAD

**Issue by DavidFaizulaev** [tulios/kafkajs#1325]
Hello,

I'm using latest version of Kafkajs and quite randomly the connection to the brokers seems to be lost and one of the errors mentioned above are generated.

I tried increasing heartbeat interval and session timeout, but nothing seems to help.
Please note that I'm running an ECS service on AWS which communicates with Kafka MSK also in AWS.

```ts
import { Consumer, Kafka } from 'kafkajs';

const kafkaInstance = new Kafka({
      clientId: 'some_client_id',
      brokers: ['brokers list'],
      ssl: true
    });

const kafkaConsumer = kafkaInstance.consumer({ groupId: 'some_consumer_group_id });
await kafkaConsumer.connect();
await kafkaConsumer.subscribe({ topic: 'some_topic', fromBeginning: true });

await kafkaConsumer.run({
      autoCommit: false, // cancel auto commit in order to control committing
      eachMessage: ... some processing function
});
```

The only thing that seems to resolve this, is using the `heartbeat` function inside of `eachMessage` function.

Please advise if I can resolve this issue without `heartbeat` function ? as I could not find a proper `sessionTimeout` or `heartbeatInterval` combination which completely removes these errors.

**Comment by noamlevy81** [comment]
What is your estimated processing time?
You tried increasing the heartbeat interval although you actually want to decrease it...

**Comment by Nevon** [comment]
Noam is right. `heartbeatInterval` is how often you want to heartbeat, and `sessionTimeout` is after how long a member should be kicked out of the consumer group if they haven't heartbeat. If you increase `heartbeatInterval` you'll heartbeat less often.

The documentation states:

> **heartbeatInterval**
> The expected time in milliseconds between heartbeats to the consumer coordinator. Heartbeats are used to ensure that the consumer's session stays active. The value must be set lower than session timeout
>
> **sessionTimeout**
> Timeout in milliseconds used to detect failures. The consumer sends periodic heartbeats to indicate its liveness to the broker. If no heartbeats are received by the broker before the expiration of this session timeout, then the broker will remove this consumer from the group and initiate a rebalance

Heatbeats happen after your `eachMessage` resolves, if at least `heartbeatInterval` ms have elapsed since the last heartbeat. A common issue people have is that their `eachMessage` takes longer than the `sessionTimeout` to complete, so it never gives KafkaJS the opportunity to heartbeat. To work around this, you can [manually heartbeat from within the `eachMessage` function](https://kafka.js.org/docs/consuming#a-name-each-message-a-eachmessage) or increase the `sessionTimeout` so that it is longer than your message processing duration (at the cost that detecting failures will take longer).

**Comment by yunnysunny** [comment]
> Noam is right. `heartbeatInterval` is how often you want to heartbeat, and `sessionTimeout` is after how long a member should be kicked out of the consumer group if they haven't heartbeat. If you increase `heartbeatInterval` you'll heartbeat less often.
> 
> The documentation states:
> 
> > **heartbeatInterval**
> > The expected time in milliseconds between heartbeats to the consumer coordinator. Heartbeats are used to ensure that the consumer's session stays active. The value must be set lower than session timeout
> > **sessionTimeout**
> > Timeout in milliseconds used to detect failures. The consumer sends periodic heartbeats to indicate its liveness to the broker. If no heartbeats are received by the broker before the expiration of this session timeout, then the broker will remove this consumer from the group and initiate a rebalance
> 
> Heatbeats happen after your `eachMessage` resolves, if at least `heartbeatInterval` ms have elapsed since the last heartbeat. A common issue people have is that their `eachMessage` takes longer than the `sessionTimeout` to complete, so it never gives KafkaJS the opportunity to heartbeat. To work around this, you can [manually heartbeat from within the `eachMessage` function](https://kafka.js.org/docs/consuming#a-name-each-message-a-eachmessage) or increase the `sessionTimeout` so that it is longer than your message processing duration (at the cost that detecting failures will take longer).

Can we call heartbeat function separately instead of calling it in `eachMessage` function? `eachMessage` function process messages one by one, if one message take long time to processed, it  will also affect the next heartbeat message sended to borker. 
[for (const message of batch.messages) {](https://github.com/tulios/kafkajs/blob/ff3b1117f316d527ae170b550bc0f772614338e9/src/consumer/runner.js#L225-L252)
