### ISSUE TITLE
Are there plans to support MockProducer and MockConsumer 

### ISSUE THREAD

**Issue by felipeplets** [tulios/kafkajs#1326]
**Is your feature request related to a problem? Please describe.**
For local development we may not need Kafka running to reduce resource consumption (running Dockerized Kafka or connecting to a cloud based service).

**Describe the solution you'd like**
Ability to mock easily mock Producer and Consumer implementations. 

**Additional context**
Examples: 

https://www.baeldung.com/kafka-mockproducer
https://www.baeldung.com/kafka-mockconsumer (https://kafka.apache.org/23/javadoc/org/apache/kafka/clients/consumer/MockConsumer.html)

**Comment by Nevon** [comment]
There are no such plans, and I'd be hesitant to take on that scope within KafkaJS itself.

@tulios wrote a package called [tiny-kafka](https://github.com/tulios/tiny-kafka) a while back that aimed to be an in-memory kafka replacement intended for testing purposes, but it hasn't been touched in 4 years and is far from complete. The benefit of the approach is that by maintaining the network boundary and using the same interface as the real thing, the client is not aware that it's not communicating with a real cluster, so all the real code and client behavior is being exercised, rather than trying to re-implement the server behavior within the mocked client itself. Similar to, for example, h2 for testing against an in-memory database.
