### ISSUE TITLE
eachBatch only consumes from one partition (2)

### ISSUE THREAD

**Issue by cybafelo** [tulios/kafkajs#1350]
I have a topic with four partitions

I am unable to consume all messages from all partitions - I only ever receive all the messages from partition 2.

This is driving me crazy - can someone help please?

---
    await this.handle.run(
        {
          partitionsConsumedConcurrently: 4,
          autoCommitInterval: 5000,
          eachBatchAutoResolve : true,
          eachBatch: async (
            {
              batch,
              resolveOffset,
              heartbeat,
              commitOffsetsIfNecessary,
              uncommittedOffsets,
              isRunning,
              isStale,
            }
          ) => {

            for (let message of batch.messages) {

              messagesReceived++;
              console.log(`Received message ${messagesReceived}`);

              if (!isRunning() || isStale()) {
                console.log(`Message is stale or not running`);
                break
              }

              resolveOffset(message.offset);

            }

            let offsets = uncommittedOffsets();

            await heartbeat();

            await commitOffsetsIfNecessary(offsets);
          }
        }
      );

**Comment by cybafelo** [comment]
Anyone?

**Comment by Nevon** [comment]
I highly doubt this is an issue with KafkaJS, since then every application using it would see similar behavior and since most of our tests use 3 partitions, they would fail.

My advice:
* Look at your metrics. Do you actually have messages in all partitions or only in the two you are receiving messages for?
  * If not, how are you producing your messages? Do you perhaps have an uneven distribution across partitions because you're using a message key that's inherently not well distributed?
* Look at your consumer group assignments. Has your consumer been assigned to all partitions?
  * If not, are you using a custom assigner that's not working correctly?
  * If yes, what's the current committed offset for your consumer group for those partitions? You haven't shared your configuration, but the default is to start from the latest offset, so unless there's messages incoming in those partitions, you won't see any messages.
* Enable debug logs and see what requests your consumer is making. Is it making fetch requests for all assigned partitions? Do you get data back? What offsets is it requesting?

**Comment by cybafelo** [comment]
Thanks alot!
