### ISSUE TITLE
Strict order of consuming

### ISSUE THREAD

**Issue by yohirusyo** [tulios/kafkajs#1368]
Hello. I have a question,
Can I get messages in 'strict' mode,? 
My consumer gets events in random ordering
1 try) 
EventDialing
EventCallCreated
EventUserDataChanged
EventUserDataChanged
EventRinging
EventReleased
EventReleased
EventCallDestroyed
2 try)
EventDialing
EventCallCreated
EventUserDataChanged
EventUserDataChanged
EventRinging
EventReleased
EventCallDestroyed
EventReleased
order I wanted)
EventCallCreated
EventDialing
EventUserDataChanged
EventUserDataChanged
EventRinging
EventReleased
EventReleased
EventCallDestroyed

**Comment by Nevon** [comment]
Messages are appended to the log in the order they are sent, and the consumer will consume in order from each partition. In order to be able to process messages in parallel on multiple consumers, you need to ensure that you partition your messages according to whatever aggregation key is relevant for your use-case. For example, in your case it seems like the events describe the lifetime of a "call", so a good key to use might be `callId`. As long as all the events relating to the same call use the same key, they will all be produced to the same partition, and thus will be consumed in order. There are no ordering guarantees across partitions.

This is not something specific to KafkaJS, so googling "kafka message ordering" will likely get you several results explaining what order guarantees you get from Kafka and how partitioning works.
