### ISSUE TITLE
Does KafkaJS spawn processes/threads per consumer

### ISSUE THREAD

**Issue by NikolayPIvanov** [tulios/kafkajs#1430]
Since the concept around NodeJS is single-threaded more or less, I've found the following statement from [Kafka: The Definitive Guide by Neha Narkhede, Gwen Shapira, Todd Palino](https://www.oreilly.com/library/view/kafka-the-definitive/9781491936153/ch04.html) quite interesting:

> You can’t have multiple consumers that belong to the same group in one thread and you can’t have multiple threads safely use the same consumer. One consumer per thread is the rule.

Does KafkaJS consumers align with the statement or they are always circling back to the main event loop/thread?

**Comment by Nevon** [comment]
That statement is very specific to the Java client. It does not hold true in NodeJS, and there's no problem having multiple KafkaJS consumers in the same NodeJS process other than the fact that they'll be competing for the same resources.

We don't spawn any worker threads or subprocesses in KafkaJS - everything happens in the main thread. Because of the single threaded nature, you don't have the same issues of thread safety (within user-land code) that you can have in multi-threaded environments. We did experiment with using worker threads for I think it was compression, since that's quite CPU intensive, but we didn't really see any real-world performance improvements at the time. It would also be interesting to execute the user's `eachMessage`/`eachBatch` functions in a worker thread, to avoid any synchronous work in there blocking any other work that needs to happen, but it would be a lot of additional complexity.

**Comment by NikolayPIvanov** [comment]
Thank you for the detailed response. I think this information would be very helpful to the community. 🚀

**Comment by NikolayPIvanov** [comment]
Thank you for the detailed response. I think this information would be very helpful to the community. 🚀
