### ISSUE TITLE
Add JMX Port and JMX Options to client configuration

### ISSUE THREAD

**Issue by 8R0WNI3** [tulios/kafkajs#1432]
**Is your feature request related to a problem? Please describe.**
I've build a small demo application which generates data, pushes them into Kafka and consumes them to store the messages in a database. The goal was to do performance tests with this sample application using Prometheus and Grafana dashboard. However, I were not able to access the producer and consumer metrics, only the ones of the broker which is running as a docker container. The problem was that with kafkajs there neither is an option to specify a JMX Port nor JMX Options. The metrics which should be accessible can be found [here](https://kafka.apache.org/documentation/#monitoring).

**Describe the solution you'd like**
Therefore, I'd suggest to add the properties JMX Port and JMX Options to the client configuration in order to be able to expose the Kafka client metrics. Otherwise, I'd have to switch to implementing my application with Java as it offers to run a Javaagent which scrapes the desired metrics.

**Comment by 8R0WNI3** [comment]
Thank you for your response. Unfortunately, I'm not able to find an instrumentation event which gives information on the average commit latency of the consumers as well as the average request latency of the producers. Am I missing them?

**Comment by Nevon** [comment]
You'll have to be more specific about what it is you're looking for. Are you talking about the total request time for OFFSET_COMMIT requests as well as the total request time for any request made by a producer? Should time spent in a queue count or just the time over the wire? Latency usually refers to the time between a packet being sent and having been received and processed on the other end, but for that you'd be looking at NodeJS metrics rather than KafkaJS metrics.

What I'm guessing you're looking for is the `REQUEST` event from either the consumer or producer namespaces. https://kafka.js.org/docs/instrumentation-events#a-name-admin-a-admin The `duration` field tells you the total time from when the action was initiated to when it was completed. `pendingDuration` is time spent in a queue before actually being sent. `apiName` tells you what protocol request the event refers to.
