### ISSUE TITLE
Add support for keys other than strings

### ISSUE THREAD

**Issue by chuck-alt-delete** [tulios/kafkajs#1544]
**Is your feature request related to a problem? Please describe.**
I would like to produce kafka record keys that are not strings (eg ints). I'm using KafkaJS version 2.2.3.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Please include links to other clients' solutions and/or KIPs for Kafka features if applicable.

**Additional context**
Here is a minimally reproducible example:
```javascript
const { Partitioners } = require('kafkajs');
const { faker } = require('@faker-js/faker');
const kafkaConfig = require('./src/kafka/kafkaConfig');

async function produce(k,v) {
    let kafka = await kafkaConfig();
    const producer = kafka.producer({
        createPartitioner: Partitioners.DefaultPartitioner
    });
    await producer.connect();

    try {
        await producer.send({
            topic: "chuck_test",
            messages: [{
                key: k,
                value: v
            }]
        }); 
    
        console.log(`key:${k}\nvalue:${v}`)
    } catch (error) {
        console.error(error)
    }
    
    await producer.disconnect()
}

let my_key = faker.datatype.number(10);
let my_value = faker.internet.email();

produce(my_key,my_value);
produce("0",my_value);
```

The first record gets an error while the second is fine.
```
{"level":"ERROR","timestamp":"2023-03-01T20:26:43.464Z","logger":"kafkajs","message":"[Producer] The \"string\" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (5)","retryCount":0,"retryTime":266}
...
key:0
value:Rafael17@hotmail.com
```

**Comment by Nevon** [comment]
So the keys in Kafka are always just _bytes_. The fact that we accept a string is just convenience because there's a default way to encode that string into a buffer ([see Buffer.from](https://nodejs.org/api/buffer.html#static-method-bufferfromstring-encoding)). But for numbers there are many ways you could choose to serialize them, big endian vs little endian, for example. That's why the input type is `string | Buffer | null`:

https://github.com/tulios/kafkajs/blob/ff3b1117f316d527ae170b550bc0f772614338e9/types/index.d.ts#L109-L110

If you want to use a number as a key you have to decide for yourself how you want that serialized. For example:

```
const key = Buffer.alloc(8)
key.writeBigInt64BE(BigInt(9007199254740991))
```

**Comment by chuck-alt-delete** [comment]
“Bring your own serializers”. Got it! Thanks!
