### ISSUE TITLE
Add experimental flag for new produce and fetch APIs

### ISSUE THREAD

**Issue by tulios** [tulios/kafkajs#163]

**Comment by ankon** [comment]
Are these flags really needed? For ZStd specifically the user would have to explicitly opt-in anyways:
1. provide a codec implementation
2. update Kafka to support the message format

From the point of view of KafkaJS it should be enough to send messages using the new produce (which assumes that we passed it through the codec which the user provided), and have Kafka accept them. For consuming similarly the gatecheck is already that we send the request and that the content is in zstd format.

Obviously there's other features than the compression change, and for these flags might come in handy.

**Comment by Nevon** [comment]
I suspect what he means with this issue is to add a temporary flag to enable those API versions to be able to selectively test this in a pre-release version. I'm not sure we need it either, since if you're running the latest pre-release you should know that there is always a chance of regressions, but that's what we've done in the past for more sensitive changes.

**Comment by tulios** [comment]
We used this approach when moving from 0.10 to 0.11 as it changed a lot of internals, but I don't think it will be necessary for v7 as you mentioned @ankon. Closing this for now.
