### ISSUE TITLE
Support private CAs similar to how node does

### ISSUE THREAD

**Issue by ctaintor** [tulios/kafkajs#32]
I suggest that we handle CAs similar to how Node does, if possible. Node uses standard CAs
and you can add more by setting `NODE_EXTRA_CA_CERTS` to extra certs. Doing it this way makes it much easier support private CAs without copying a bunch of boilerplate code.

**Comment by tulios** [comment]
I've tested the `NODE_EXTRA_CA_CERTS` env and it works fine, there might be other issues like (due to the test environment):

![screen shot 2018-04-04 at 19 39 18](https://user-images.githubusercontent.com/33231/38324223-ebfc68a2-383f-11e8-9ffc-9a7a518d725a.png)

But using the following configuration it works fine:
```javascript
{ ssl: { servername: 'localhost' } }
```

![screen shot 2018-04-04 at 19 37 21](https://user-images.githubusercontent.com/33231/38324153-bb259ff0-383f-11e8-8e4a-aeecdbefb358.png)

But on a production server, this might not be necessary. The SSL block must be present to use the TLS socket, but it can be set to true.

I'll add this to the readme.

**Comment by tulios** [comment]
Fixed on `v1.0.0`
