### ISSUE TITLE
getTopicMetadata() returns empty array although topics exist

### ISSUE THREAD

**Issue by ManfredLange** [tulios/kafkajs#328]
This works:
```
let topicMetadata = await admin.getTopicMetadata({ topics: ["test-topic"] });
```
It returns the metadata for the given topic as expected.

**Actual behavior:** The following returns empty collection of topics:
```
let topicMetadata = await admin.getTopicMetadata({ topics: undefined });
```

**Expected behavior** is for the second call to return the metadata for all topics including the metadata for topic "test-topic".

**Environment:**
- Kafkajs version 1.6.0
- @types/kafkajs version 1.4.1
- Kafka 2.11 via docker image `wurstmeister/kafka:2.11-1.1.1`
- TypeScript 3.4.1

**Comment by Nevon** [comment]
Thanks for the very clearly explained ticket! ⭐️

We discussed this yesterday in regards to #325. I'm a bit surprised at your results, actually. Are you creating a new admin client in between those two calls?

The way it works right now is that on the first call, where you are specifying the topic, we fetch metadata and then add that topic to a list of target topics. On the second call, if you don't specify any topics, we use the list of target topics, which means that you should get back metadata for `test-topic` again.

The jsdoc actually mentions this behavior:

https://github.com/tulios/kafkajs/blob/1bc6e09be6c567be089e3cb63ace8c9b819f6e0d/src/admin/index.js#L474-L475

Note the part where it says "of which we are aware". As far as I know, we don't really claim anywhere that if you don't specify any topics, we'll return metadata for all topics, although I agree that that would be a reasonable API.

So, I agree with you that this is something that needs to be improved, but I would say it's a poorly thought out API rather than a bug. Changing this behavior now would be an API breaking change, so maybe a more likely change would be that we deprecate `getTopicMetadata` and create a new method that behaves the way you describe.

**Comment by tulios** [comment]
Yeah, this is a weird behavior and I don't think anyone is relying on it. Like @nevon mentioned, we have a PR about the same thing, I will take some time and improve this method.

**Comment by ManfredLange** [comment]
Thank you, @Nevon and @tulios, for the fast response.

Each of the above calls is a separate test run, so each creates a new admin client that connects, makes the call and then disconnects.

I had a look at [https://kafka.apache.org/protocol#The_Messages_Metadata](https://kafka.apache.org/protocol#The_Messages_Metadata) (mentioned in the code snippet in @Nevon's  reponse) and there it reads:

> If the topics array is null fetch metadata for all topics.

It appears as if this is not working as documented on Apache's site, or perhaps I'm misunderstanding their docs.

I believe, though, that there is a query endpoint available if you have Exhibitor running as a co-process for your Zookeeper(s) (ZKs). In the interim I'll explore this option as we have Exhibitor in our deployment.

It would still be nice if the admin client of `kafkajs` had a good method to obtain the metadata as well. I don't know enough about the brokers or ZKs to state if they even offer a reliable API for that that `kafkajs` could build on.

And yes, I think the `listTopics()` option suggested in #325 instead of changing the behavior of `getTopicMetadata()` is probably the better option. I'll subscribe to 325 and close this issue.

Thank you for your assistance! Keep up the great work!
