### ISSUE TITLE
Large batches take exponentially longer to encode

### ISSUE THREAD

**Issue by colinfindlay-nz** [tulios/kafkajs#383]
Hi,

We're currently seeing issues with very large message batch sizes.
If we send a message[] of approx 1,000 messages - it's taking about 200 milliseconds to encode. With 10,000 messages it's taking a lot longer - as much as 12 seconds in my rough tests.

I believe the problem is with how the RecordBatch encoder iterates over arrays:
```
  if (compression === Compression.None) {
    batchBody.writeArray(records)
  } else {
    const compressedRecords = await compressRecords(compression, records)
    batchBody.writeInt32(records.length).writeBuffer(compressedRecords)
  }
```

```
const compressRecords = async (compression, records) => {
  const codec = lookupCodec(compression)
  const recordsEncoder = new Encoder()

  for (let record of records) {
    recordsEncoder.writeEncoder(record)
  }

  return codec.compress(recordsEncoder)
}
```

In both instances this ends up in `encoder.writeEncoder(value)` - which performs a simple `Buffer.concat` - unfortunately this doesn't scale when callled in a loop, resulting in large amounts of buffer cloning.

A quick proof-of-concept hack to take an array and write it as a single concat, rather than many showed a performance improvement of about 1200% 

Is it possible to improve this?

**Comment by Nevon** [comment]
Yes, absolutely! The encoder very naively copies buffers constantly, which is very inefficient. I've been wanting to replace the buffer usage with something that over-allocates buffer space, allowing us to add to the buffer without necessarily cloning the whole thing, but I haven't found the time to drive the change to completion.

If you believe you can turn your proof-of-concept hack into a decent PR, then that's a good quick win.

**Comment by tulios** [comment]
WeHi @colinfindlay-nz, it was a conscious decision to use `Buffer.concat` on the encoder implementation, we wanted to nail the first implementation, and it was easier to achieve that with `concat`. We are aware that the performance can be improved, and most of the code that manipulates buffers are concentrated on the `Encoder` class. We had a discussion some months ago about tackling this, but we decided that it wasn't the time.

We have an extensive code coverage on the protocol parts, so if you want to give it a try. We will improve the performance of the encoder; it's just a matter o priority. We have some requirements on the new authentication methods so that we might look at this again after that.

**Comment by colinfindlay-nz** [comment]
I can probably find time to knock something up, just thinking off the top of my head - would you want `writeEncoder` to detect arrays and change the calling functions to pass in these arrays, or a seperate encoder function `writeEncoderArray`?
We could try and do something that over-allocates buffer-space, but the problem with this approach is that it will always be wrong, resulting in either unwanted extra allocations or excessive memory usage in most scenarios.

**Comment by tulios** [comment]
Improved on #394, we still have plans to improve the encoder/decoder performance. I will close the issue but feel free to re-open it if you need.
