### ISSUE TITLE
Using Kafkajs in an Ionic Angular app, real time chat app.

### ISSUE THREAD

**Issue by dluisbrbr** [tulios/kafkajs#426]
I would like to know if it is possible to use KafkaJs in an application that is being developed in Ionic 4 / Angular 7, the app should treat millions of requests for messages (chat), we intend to use Kafka for messaging.
To do so we will develop the backend in node, to treat messages / persistence and publication of topics.
We are looking for a package that can be used in both the back and the frontend javascript.
Would anyone know if Kafkajs could be used in this scenario?

Tks

**Comment by Nevon** [comment]
The short answer is that KafkaJS does not currently work in a browser environment. It is targeting NodeJS. There are currently no Kafka clients available that work in a browser, to the best of my knowledge. However, KafkaJS can indeed be used to power a chat application (we are in fact doing that ourselves), but only on the backend. You would need to set up a websocket connection or some other push based technology to do the frontend<->backend communication.

The longer answer is that the communication between the Kafka client and the Kafka brokers is done via TCP sockets. This is a low-level interface that is not available in browsers. This means that it's not possible for the web browser to talk directly to Kafka. This is why there's no Kafka client that works in a browser. We have done a proof-of-concept where we use a custom socket implementation that uses websockets instead. This is not a 1-to-1 swap, as despite them both having the word socket in their name they are quite different. In this scenario, the client establishes a websocket connection to a proxy service that basically just forwards the data over a plain TCP socket to the Kafka broker. That allows you to run KafkaJS in the browser, since the rest of it is just plain old Javascript that runs in pretty much any environment.

It works, but I haven't found any open-source implementation of this that I would consider production quality, so there's definitely some work involved to make it work properly (if anyone wants to sponsor that work, get in touch!)

I should really write an FAQ entry about this, as it comes up rather frequently.

**Comment by edubois10** [comment]
@Nevon, do you know if this is this still the case? I would like to use kafka packages (kafkajs or kafka-node) in a vuejs application, but unfortunately, I didn't find anything that could help me.
