### ISSUE TITLE
Is it possible to find out which partition a consumer belongs to?

### ISSUE THREAD

**Issue by ThisIsMissEm** [tulios/kafkajs#442]
I'm currently working on an application that follows the Kappa architecture, and I'm I little stuck on one issue: When my application starts, I need to read an entire kafka topic into memory, and then once I've read to the latest message, I need to signal that the application is ready to start accepting requests (that is, it's as up-to-date as it can possibly be)

The way I was thinking of solving this was to use offsets:

1. Get the current topic offsets using `admin.fetchOffsets()`
2. Create a consumer using a non-unique group ID using `fromBeginning = true`
3. seek the consumer to the -1 offset as to rebuild the database
4. once my consumer's `eachMessage` receives a message where the offset read from admin.fetchOffsets() for my partition is equal to the message's offset and partition, emit an event "ready"

But it seems that it's not possible to know outside of eachMessage as to what the consumer's partition is. And `consumer.seek` doesn't seem to make my eachMessage begin to get called again.

Is there any information on how to correctly do this?

**Comment by JaapRood** [comment]
Cool to see someone else attempting this architecture in Node! 🎉 In basic steps, this is what you most likely want to do for Kappa:

- Create a Consumer and _subscribe_ it to the input topic, the messages you actually want to process.
- Listen to the `consumer.GROUP_JOIN` events, as the ConsumerGroup will assign each active Consumer a set of partitions it's responsible for processing for. It passes `memberAssignment`, which is a list of topics and partitions your consumer instance is responsible for processing.
- For each partition you got assigned: pause the consumption using `consumer.pause`.
- For each partition you got assigned: use a second consumer to read the processing state into memory (or wherever else you're keeping it). Unfortunately, there's one missing puzzle piece in KafkaJS here: manually assigning partitions to a kafka consumer (#373). When supported, this should let you assign the exact partition and starting offset (-1 as you mentioned to ensure a full restore!). Once you reached the last message (`eachBatch` passes the current highwater offset along with it If I'm not mistaken), you should be done.
- For each partition: resume using `consumer.resume` and start to process mesages!

Now instead of being able to manually _assigning_ partitions, you technically _can_ go the route of _subscribing_ with a unique `groupId` and simply skip processing the messages with the wrong partition. However, I would not recommend it, as it creates a pretty nasty overhead in terms of fetching lots of messages you don't need, creating lots of consumer groups that become hard to manage and monitor performance for, etc.

**Comment by tulios** [comment]
I think there is a simple way, we have an application that does exactly what you want. Like @JaapRood said, use `consumer.events.GROUP_JOIN` to pick the assigned partitions and use seek to move to the beginning. Use `eachBatch` instead of `eachMessage` so you can check if the message is stale, as the seek wasn't performed yet.

**Comment by ThisIsMissEm** [comment]
@JaapRood okay, so, I'm still learning Kafka, but our approach is actually to keep all the data in memory — rather than storing it in a temporal or cached database (e.g., redis).

> use a second consumer to read the processing state into memory (or wherever else you're keeping it)

Do you mean that I'd have a kafka topic which is something like `${topic}-state` or something?

Oddly, I've read almost every article I can find about kafka+kappa, and honestly, I've not yet once seen an actual example of the code required to do full-kappa without using a separate database (e.g., redis)

**Comment by ThisIsMissEm** [comment]
@JaapRood if I'm understanding you correctly, then the interface of `IMemberAssignment` is that the key is the assigned `topic` and the value is the `partition`, correct?

**Comment by ThisIsMissEm** [comment]
@JaapRood / @tulios — does `consumer.run`'s `eachMessage` use zero-based offsets, yet `admin.fetchOffsets` return 1-based offsets?

Noticing that I seem to never get to the last offset in `eachMessage`.

**Comment by tulios** [comment]
@ThisIsMissEm the message has the committed offset, the offset where the message is, but Kafka store the next offset, so if you processed offset 14 it means that your consumer group is in the offset 15, the next offset to fetch is 15.

**Comment by ThisIsMissEm** [comment]
Okay, so, to check if I'm at the correct offset I'd need to do `message.offset + 1 === partition.offset`

**Comment by ThisIsMissEm** [comment]
@tulios @JaapRood Is there any way to get the count of messages in a given topic in kafka?

I've noticed that under certain conditions my code can get into a state where it thinks the consumerGroup offset is -1, and as such, I don't know how many messages are remaining on the kafka topic at the time of connection.

**Comment by JaapRood** [comment]
@ThisIsMissEm my example totally assumed that you're processing messages from an input to an output topic, using intermediary state! The extra steps I described around subscribing, pausing and resuming all are specific to that usecase. It seems, though, that you're just trying to read an existing topic of data into memory. If so, a single consumer would suffice, but manual assignment (still working on it!) would be the preferred way of consuming the required partitions.

> @JaapRood if I'm understanding you correctly, then the interface of IMemberAssignment is that the key is the assigned topic and the value is the partition, correct?

Correct!

> Okay, so, to check if I'm at the up-to-date offset I'd need to do message.offset + 1 === partition.offset

Correct once again!

> Is there any way to get the count of messages in a given topic in kafka?

Kafka allows fetching the low and high watermarks of a partition, which means the lowest number offset available in the log and the highest produced thus far. If you're trying to determine whether you've "caught up", you use the the logic you described above on every message. To cover the case when a topic is empty, you can use the result of `admin.fetchTopicOffsets` to compare high and low watermarks:

```js
await admin.fetchTopicOffsets(topic)
// [
//   { partition: 0, offset: '31004', high: '31004', low: '421' },
//   { partition: 1, offset: '54312', high: '54312', low: '3102' },
//   { partition: 2, offset: '32103', high: '32103', low: '518' },
//   { partition: 3, offset: '28', high: '28', low: '0' },
// ]

// `(high - low) < 1` means there shouldn't be any messages to consume!
```

Small technical note: because of Kafka's various compaction strategies, you can't get an accurate count of messages from `high - low`.

**Comment by tulios** [comment]
@ThisIsMissEm feel free to re-open the issue if you need.

**Comment by ThisIsMissEm** [comment]
For now we've opted to not go full kappa; the details on practically implement it just aren't there, and it sounds like kafkajs still needs features to make it properly work.

**Comment by JaapRood** [comment]
@ThisIsMissEm seems like a wise decision, will save you a lot of time until we get better primitives. For my client projects we've developing such a framework, given the great potential the architecture has, but it's been a lot of work to really get a robust system going. I've actually started the extraction of that into an open source library last week here: https://github.com/jaaprood/frolyk (actually while live-streaming 😅). That's not anywhere near functional yet, but might be something to keep an eye on.
