### ISSUE TITLE
Consumer Events - knowing which are fatal  to expose the data to a health endpoint?

### ISSUE THREAD

**Issue by appsolutegeek** [tulios/kafkajs#500]
Hi,

I am currently exposing a health endpoint which returns a boolean if kafka is healthy, i use the heartbeat event here to detect if the last heartbeat was greater than the session timeout. 

If i class it as being healthy, i would like to expose the last event of the issue.

I am seeing the following events

I think CRASH is obvious, and this is an ERROR, Connect and Disconect,  i presume can happen throughout its connection life and not considered an error ?

The stop event, when does this happen, this could happen under normal circumstances or only when an error ?

The CRASH event - always happens when there is a problem ? Can I depend on it ?

I would like to know the event data that I should expose to my health endpoint when I am classed as unhealthy - any ideas ??

Thanks in advance

```
    this.kafkaConsumer.on(this.kafkaConsumer.events.CONNECT, e => {
      if (logger.isDebugEnabled()) {
        logger.debug("Kafka event [CONNECT] received", e)
      }
    })

    this.kafkaConsumer.on(this.kafkaConsumer.events.DISCONNECT, e => {
      if (logger.isDebugEnabled()) {
        logger.debug("Kafka event [DISCONNECT] received", e)
      }
    })

    this.kafkaConsumer.on(this.kafkaConsumer.events.CRASH, e => {
      if (logger.isErrorEnabled()) {
        logger.error("Kafka event [CRASH] received", e)
      }
    })

    this.kafkaConsumer.on(this.kafkaConsumer.events.STOP, e => {
      if (logger.isDebugEnabled()) {
        logger.debug("Kafka event [STOP] received", e)
      }
    })
```

**Comment by Nevon** [comment]
Stop happens when you call `consumer.stop` or when the consumer is disconnecting (such as when you call `consumer.disconnect`).

> The CRASH event - always happens when there is a problem ? Can I depend on it ?

The crash event is triggered whenever there is an unhandled error. It should always be triggered when there is something that KafkaJS cannot deal with and has to restart. That doesn't mean that this is the only scenario in which your consumer is unable to do its job. For example, let's say you try to access your database for each message, but access times to your database becomes really high for some reason. Now processing each message is so slow that you end up not heartbeating within the session timeout, and your consumer becomes unhealthy as a result. There's nothing KafkaJS can tell you about why it's unhealthy, other than that you didn't heartbeat.

> I would like to know the event data that I should expose to my health endpoint when I am classed as unhealthy - any ideas ??

What we generally do is use the heartbeat to determine if it is healthy or not. For additional information, we typically produce metrics or logs, but you could also include information on the consumer group state: https://kafka.js.org/docs/consuming#a-name-describe-group-a-describe-group

This way you can know if the reason your consumer is not heartbeating is because the group is currently rebalancing, for example.

**Comment by appsolutegeek** [comment]
Great! Thanks for the prompt reply.  Much appreciated. I will look into describeGroup.
