### ISSUE TITLE
Does this library have a good way to consume topics windowed by time?

### ISSUE THREAD

**Issue by edwmurph** [tulios/kafkajs#516]
I am trying to reduce the resolution of my input data to aggregations of 5s intervals for analysis.

I believe this could be accomplished using [streams](https://kafka.apache.org/documentation/streams/) but this library doesn't seem to have an implementation for that kafka api?

related https://github.com/tulios/kafkajs/issues/298

**Comment by JaapRood** [comment]
Kafka Streams is definitely how you would do that in Java, where the Streams library comes bundled with the Kafka client. KafkaJS, however, is and aims to be just the client. Any Streams logic could be implemented on top, just like Kafka Streams was. 

I've started [an implementation](https://github.com/jaaprood/frolyk) of such a Stream processing library built on top of KafkaJS, but the base isn't anywhere near functional yet, let alone higher level ideas like windowing. I don't really know of any other libraries like that.

Until then, I'd suggest reading up on how Kafka Streams implements the windowing and doing it manually for now. It's all based on the basic abilities of a Kafka client, so it's all technically and conceptually possible, just still quite a bit of work to figure it all out 😅.

**Comment by edwmurph** [comment]
Could windowing be accomplished using [`eachBatch`](https://kafka.js.org/docs/consuming#a-name-each-batch-a-eachbatch)?

In other words, when processing a batch could `resolveOffset` be used to only commit the offsets for the messages in the current desired time window? Then subsequent batches would start from the beginning of the subsequent desired time window right?

**Comment by JaapRood** [comment]
> In other words, when processing a batch could resolveOffset be used to only commit the offsets for the messages in the current desired time window? Then subsequent batches would start from the beginning of the subsequent desired time window right?

I'm pretty sure that won't work. But even if it did, I'm really doubt it's a good idea. Committing offsets in Kafka (generally, not just KafkaJS) is purely meant as a fault tolerance mechanism, to continue processing where you left off before. 

> Could windowing be accomplished using eachBatch?

It's definitely possible, just like it is with any other Kafka client! Remember, _Kafka Streams_ is a library built on top of the base Java Kafka client. However, the details on how to approach that are a bit too much to address in an issue like this, because it would basically require explaining all log based system design! I can recommend some books that'll point you in the right direction, though: 

- [Designing Event-Driven Systems](https://www.goodreads.com/book/show/39793332-designing-event-driven-systems) by Ben Stopford. Goes into great detail on how these types of systems are built.
- [Designing Data-Intensive Applications](https://www.goodreads.com/book/show/23463279-designing-data-intensive-applications) by Martin Kleppmann. A lot more general, but with some great chapters on event log based programming as well. 

There's tons of other resources out there as well (like articles, videos, etc.), but I always end up losing track of those.

**Comment by edwmurph** [comment]
thank you
