### ISSUE TITLE
kafka js not consuming messages

### ISSUE THREAD

**Issue by rubiin** [tulios/kafkajs#561]
I have consumer and producer setup in two different node apps.Sometimes the consumer doesnt consume messages even though the producer has successfully published the message

**Comment by rubiin** [comment]
@tulios

**Comment by JaapRood** [comment]
That's unfortunate! What have you done thus far to try and diagnose the problem? Perhaps you can run consumer with [logging](https://kafka.js.org/docs/configuration#logging) so we _might_ be able to see what's going on.

**Comment by tulios** [comment]
@rubiin, can you describe the flow? This is a common misunderstanding where you publish a message and then boot the consumer with the default configuration, which is to start from the latest offset.

**Comment by rubiin** [comment]
@JaapRood i will try to add the logger and see what it shows

**Comment by rubiin** [comment]
I get this log when i add the error log :
```
ERROR [Runner] The coordinator is not aware of this member, re-joining the group {"timestamp":"2019-11-27T10:36:20.445Z","logger":"kafkajs","groupId":"nestjs-group-server","memberId":"nestjs-consumer-server-08042167-cb96-4eaf-b952-d3566ad92223","error":"The coordinator is not aware of this member","retryCount":0,"retryTime":278}
```

**Comment by JaapRood** [comment]
That's _something_, but still not that much to go off. If you'd run with `logLevel: logLevel.INFO`, we should be able to get a lot more insight in what the consumer is up to.

**Comment by noam-worthy** [comment]
> @rubiin, can you describe the flow? This is a common misunderstanding where you publish a message and then boot the consumer with the default configuration, which is to start from the latest offset. If that's not the case, maybe you can share some logs.

@tulios From tests i've made locally, it looks like if I start a consumer with an active consumer group - the consumer will pick up from where the consumer group is at. Not from the latest offset. Or am I missing something?

**Comment by rubiin** [comment]
@noam-worthy the flow is of pub sub architecture where one of my app is producer and another consumes the produced messages. But sometimes the consumer doesn't consume messages even though they are produced in the topic

**Comment by rubiin** [comment]
@JaapRood is there a way to set multiple log levels ??

**Comment by noam-worthy** [comment]
@rubiin what tulios said refers to this part of the documentation: https://kafka.js.org/docs/consuming#a-name-from-beginning-a-frombeginning

My comment was that in local tests i've made i saw different behavior, and I am relying on it. Though I am also experiencing 'stuck' partitions, so perhaps my local test was not performed properly. 

I'm trying to debug my issue as well and will update you if I find anything.

**Comment by noam-worthy** [comment]
Regarding log levels, If you set the log level to 'info' - you will get all logs of: info, warning, error, critical.

**Comment by Nevon** [comment]
> From tests i've made locally, it looks like if I start a consumer with an active consumer group - the consumer will pick up from where the consumer group is at. Not from the latest offset. Or am I missing something?

Yes. If the consumer group has already committed an offset, it will continue from there. If it is a new consumer group, or if it has been inactive long enough for the committed offset to no longer be retained, it will start consuming from either the beginning of the topic or from the latest offset of the topic, depending on how it's configured. The default configuration is to start from the latest offset. The `fromBeginning` flag only controls the _default_ behavior, when there is no consumer group offset to continue from.

**Comment by rubiin** [comment]
@noam-worthy I see in docs , that info log is the default one if no logging is set explicitly

**Comment by jasine** [comment]
I have similar situation, my consumer stuck and not consume message anymore

**Comment by ulloa** [comment]
I actually had a similar issue just now. I described Kafka consumer groups in the console. And my kafkajs consumer group wasn't moving up in offset, the lag was increasing after every message I sent.

I restarted the node server and kafkajs consumer multiple times and logged everything, but the only log that had any extra info was DEBUG. However it was too long to read (50 MB of logs in a minute or so), saying this over and over: `{"level":"debug","message":"Fetching from 1 partitions for 1 out of 1 topics","extra":{"timestamp":"2019-12-25T20:19:00.871Z","logger":"kafkajs","topics":["results"],"activeTopicPartitions":[{"topic":"results","partitions":[0]}],"pausedTopicPartitions":[]}}
{"level":"debug","message":"Request Fetch(key: 1, version: 7)","extra":{"timestamp":"2019-12-25T20:19:00.871Z","logger":"kafkajs","broker":"Locke:9092","clientId":"API","correlationId":85563,"expectResponse":true,"size":92}}
{"level":"debug","message":"Response Fetch(key: 1, version: 7)","extra":{"timestamp":"2019-12-25T20:19:00.871Z","logger":"kafkajs","broker":"Locke:9092","clientId":"API","correlationId":85563,"size":147,"data":"[filtered]"}}
`
I tried admin.resetOffset, but I get this error: `Error: Executing consumer group command failed due to java.lang.IllegalArgumentException: Invalid negative offset` because it sets it to -1 offset. Then I just used admin.fetchOffsets to set the consumer offsets using admin.setOffsets to the latest offset, it seems to be working as expected for now and I can work around it using these admin functions if there were some sort of event that tells me it is stuck.

**Comment by ulloa** [comment]
I actually had a similar issue just now. I described Kafka consumer groups in the console. And my kafkajs consumer group wasn't moving up in offset, the lag was increasing after every message I sent.

I restarted the node server and kafkajs consumer multiple times and logged everything, but the only log that had any extra info was DEBUG. However it was too long to read (50 MB of logs in a minute or so), saying this over and over: `{"level":"debug","message":"Fetching from 1 partitions for 1 out of 1 topics","extra":{"timestamp":"2019-12-25T20:19:00.871Z","logger":"kafkajs","topics":["results"],"activeTopicPartitions":[{"topic":"results","partitions":[0]}],"pausedTopicPartitions":[]}} {"level":"debug","message":"Request Fetch(key: 1, version: 7)","extra":{"timestamp":"2019-12-25T20:19:00.871Z","logger":"kafkajs","broker":"XXX:9092","clientId":"API","correlationId":85563,"expectResponse":true,"size":92}} {"level":"debug","message":"Response Fetch(key: 1, version: 7)","extra":{"timestamp":"2019-12-25T20:19:00.871Z","logger":"kafkajs","broker":"XXX:9092","clientId":"API","correlationId":85563,"size":147,"data":"[filtered]"}}`
I tried admin.resetOffset, but I get this error: `Error: Executing consumer group command failed due to java.lang.IllegalArgumentException: Invalid negative offset` because it sets it to -1 offset. Then I just used `admin.fetchOffsets` to set the consumer offsets using `admin.setOffsets` to the latest offset, it seems to be working as expected for now and I can work around it using these admin functions if there were some sort of event that tells me it is stuck.

**Comment by Nevon** [comment]
@ulloa: That the size is 92 bytes tells me that the batch was empty. There can be many reasons for this, such as having a single message that is too big to fit into a batch, or that the whole batch is full of compacted messages. If it's the latter, there is a workaround [available in the latest beta version](https://www.npmjs.com/package/kafkajs/v/1.12.0-beta.17) if you want to give that a shot.

This issue is now containing many different questions about several different topics, so I'm gonna close this. Feel free to open new issues for specific things if needed.
