### ISSUE TITLE
is kafkajs supports kafka@v2.11?

### ISSUE THREAD

**Issue by lzj723** [tulios/kafkajs#564]
i always get an error when connect to kafka@v2.1.1:

Code:
```javascript
const kafka = new Kafka({
  clientId: 'clientid_001',
  brokers: ['x.y.z'],
  sasl: {
    mechanism: 'scram-sha-256',
    username: 'xxx',
    password: 'xxxxxx',
  },
});
const producer = kafka.producer();
producer.connect();
```

Error:
```javascript
{ KafkaJSSASLAuthenticationError: SASL SCRAM SHA256 authentication failed: Authentication failed due to invalid credentials with SASL mechanism SCRAM-SHA-256
    at SCRAM256Authenticator.authenticate (/xxx/node_modules/kafkajs/src/broker/saslAuthenticator/scram.js:157:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'KafkaJSSASLAuthenticationError',
  retriable: false,
  helpUrl: undefined }
```

**Comment by tulios** [comment]
Hi @lzj723, since you are using SCRAM you might need to enable SSL, the broker is probably rejecting the call because of that.

Add `ssl: true` to the configuration, or configure with the correct certificates, etc and it should work. KafkaJS works with Kafka 2.1.1, that's the version we use in production.

@Nevon just an idea, maybe we should have an entry on the FAQ about auth mechanisms without SSL and then update the `helpUrl` on the errors

**Comment by Nevon** [comment]
Created #565 to track.

**Comment by tulios** [comment]
Closing this issue for now, if what I mentioned is not the case feel free to re-open the issue.
