### ISSUE TITLE
I want to adjust max.poll.interval.ms

### ISSUE THREAD

**Issue by zepeto-dev** [tulios/kafkajs#574]
there is a long batch job. It can be processed up to 1 to 2 hours.
I have to do it with 1 eachMessage.
poll one message and not poll the message until the time it is processed.
that's why I have to modify **max.poll.interval.ms**
how should I fix it in kafkajs?
what I want is that rebalancing doesn't happen even if it hasn't been processed for an hour.
**session.timeout.ms
group.min.session.timeout.ms**
both options are handled by the broker, so I modified them, but I don't know how to modify max.poll.interval.ms.
Can you tell me the best option?

**Comment by JaapRood** [comment]
When running processing that's this long and can't be broken up in smaller steps, you'll want to use `eachBatch` instead of `eachMessage`. That's because you'll need to call the `heartbeat` function  it provides at least once within `session.timeout.ms`. [The documentation](https://kafka.js.org/docs/consuming#a-name-each-batch-a-eachbatch) should help you along with how to implement that. 

This heartbeat is the consumer's way to letting the Broker know it's still alive and healthy, busy processing. Without it, the Broker can't know whether the consumer is just processing for a very long time, or has crashed, lost connection to the Broker, etc. That's also the reason why changing those timeouts won't give the effect you're after. The time-outs are an integral part in the fault-detection mechanisms of Kafka.

The processing of a single message taking hours is something trying to avoid. Not only because of the above, but also if you consider what happens if a crash _does_ happen within processing. All of it would have to be done again. When a problem is split up into smaller chunks, it's easier to prevent having to redo lots of work.

**Comment by NoahHahm** [comment]
@JaapRood 
thank you for the answer.
Distributing messages across partitions from producers In a Consumer Group, instances read and process messages one by one.
for eatchBatch why is it ignored even if I set partitionsConsumedConcurrently to 1?
how can I ensure that I get 1 message from eachBatch?

**Comment by Nevon** [comment]
> how can I ensure that I get 1 message from eachBatch?

You cannot. You can configure how many bytes you want to get in each batch, and how long to wait for getting that number of bytes, but you cannot ask for a specific number of messages.

That's not really an issue, however, as you do get an array of messages in the `eachBatch` handler, so you just need to process them one by one in sequence. The `eachBatch` example in the documentation that @JaapRood linked you to does exactly that.
