### ISSUE TITLE
Not reading another topic in parallel

### ISSUE THREAD

**Issue by goriunov** [tulios/kafkajs#579]
Is it expected that if my consumer subscribed to multiple topics it is not going to read them in parallel ? For example if i have 2 topics and one of them takes too long to process messages how can i read from another topic within that time ?

**Comment by goriunov** [comment]
So the only solution is to pause and resume topic:
```
 eachBatch: async (eachBatch: EachBatchPayload) => {
                this.consumer.pause([{ topic: eachBatch.batch.topic }]);
                this.processBatch(eachBatch, () => {
                    this.consumer.resume([{ topic: eachBatch.batch.topic }]);
                });
            }
```

**Comment by tulios** [comment]
Hi @goriunov, I am leaving this comment as a future reference for other users that might land on this issue.

The concurrency unit in Kafka is the partition, KafkaJS can process each partition in parallel regardless of the topic. There are limitations to this approach; even if you subscribe to several topics, the library will fetch data based on `maxBytes` and `maxBytesPerPartition`. This means that if these attributes aren't correctly configured (the default is 10mb and 1mb, respectively), the Kafka brokers might return data for a single topic. KafkaJS doesn't process the partitions in parallel by default. https://kafka.js.org/docs/consuming#concurrent-processing

On another note, KafkaJS doesn't process messages in parallel as this would break the order guarantees that Kafka has, but it offers an escape hatch. The `eachBatch` callback has access to the entire batch (for a single partition at a time) and can process the messages in parallel if you wish. Keep in mind that it is a good idea to call the heartbeat function in between each message. Otherwise, the broker might kick the consumer from the group if the processing takes too long. You can read more about what is exposed on each batch here: https://kafka.js.org/docs/consuming#a-name-each-message-a-eachmessage
