### ISSUE TITLE
Is it possible check that Kafka producer is successfully connected?

### ISSUE THREAD

**Issue by serragnoli** [tulios/kafkajs#591]
(Pretty much the question asked in #452 but for Producers)

I would like to expose a health check endpoint from my application that produces data to Kafka.

Based on the replies on #452, I think I should/could use the [REQUEST_QUEUE_SIZE](https://kafka.js.org/docs/instrumentation-events#a-name-producer-a-producer) event.
Is this a good option? Is there any other alternative besides the above event?

**Comment by Nevon** [comment]
Healthchecking for producers doesn't really make much sense, in my opinion.

`await producer.connect()` will tell you if you managed to establish a connection, but after that, if you're not sending any data, you have no idea if the connection is still open. A TCP connection is not closed until one side sends a close packet.

When you call `await producer.send()`, KafkaJS will re-establish the connection if it turns out that the other side has closed it without letting us know. If it fails to re-establish the connection after some retries, it will throw so that you will know that it failed.

Consumer groups have a state that you can periodically check on with a healthcheck. Producers don't really work the same way, so monitoring them in the same way is not really the way to go. I would instead base my monitoring on metrics on the errors that are thrown, or something like that. It doesn't matter if your producer is connected or not if you're not sending any messages. The only thing that matters is that it succeeds when you are sending something.

**Comment by serragnoli** [comment]
Thanks for the reply @Nevon. I was away and returning to this issue today.

I have a follow-up question please.

> If it fails to re-establish the connection after some retries
Is the number retries configurable?

**Comment by neeraj-vts** [comment]
@Nevon I am looking for same thing check , and read you comment above . 
`await producer.connect() will tell you if you managed to establish a connection`
But its not returning anything and not throwing any kinda exception or something , Its just the debug log only .

How can i check if producer.connect() was successful ?

**Comment by Nevon** [comment]
It returns a promise. If that promise resolved, it connected. If it rejects, it failed to connect.
