### ISSUE TITLE
issue with producer/consumer batching

### ISSUE THREAD

**Issue by Viral** [tulios/kafkajs#596]
I have a simple producer/consumer somewhat working using the sample code. All of a sudden my consumer, which uses eachBatch started breaking up the batches...

on the producer I have something like this:

```
await producer.send({
    topic: 'test-topic',
    messages: [
      {"CHD" : 452345235423},
      {"KEY" : "55"},
      {"REASON": "unknown"}     
    ],
  })
```

and the consumer is

```
await consumer.run({
  eachBatch: async ({ batch, resolveOffset, heartbeat, isRunning, isStale}) => {
    const data = {};
    for (let message of batch.messages) {
      data[message.key.toString()] = message.value.toString();
      resolveOffset(message.offset);
      await heartbeat();
    }
    console.log(JSON.stringify(data));
  }
});
```

I get a batch of 1 key/value and then the 2nd batch will have 2 of the key/value pairs. it's random. but the 3 key/value pairs are never in the same batch. what am I doing wrong? what am I not understanding?

**Comment by Nevon** [comment]
The concept that you are missing is that producing a batch of messages has nothing to do with consuming a batch.

In Kafka, messages are stored in a partitioned log in the order that they were produced. When you consume, you simply ask for a certain number of bytes from a certain offset on one of those partitions - we call that a batch. The only difference between the `eachMessage` and `eachBatch` interfaces that we expose is whether we feed you one message at a time or if you give you all the messages in that batch at once.

Producing multiple messages in a single `producer.send` call has no bearing whatsoever on how those messages are consumed later on. It's just a way to reduce the number of requests you make.

Moreover, the format that you are sending your message in is not valid. This is what a valid send call looks like:

```js
await producer.send({
    topic: 'topic-name',
    messages: [
        { key: 'key1', value: 'hello world' },
        { key: 'key2', value: 'hey hey!' }
    ],
})
```

Note how each message has a key and a value. The key is used to determine which partition the message ends up in, so if you need the messages to be consumed in a certain order, you need to make sure that they have the same key so that they end up in the same partition. The `value` is where you put your actual payload.
