### ISSUE TITLE
Produced messages lost when KafkaJSNumberOfRetriesExceeded is raised

### ISSUE THREAD

**Issue by robodude666** [tulios/kafkajs#628]
I'm noticing that any messages the producer attempted to send out are lost if `KafkaJSNumberOfRetriesExceeded` is raised. Based on the [retry](https://github.com/tulios/kafkajs/blob/baabae3e52a34cf77910d47c547ea9f4d5a5de8f/docs/Configuration.md#-default-retry) documentation this sounds expected.

Would it be in scope of `kafkajs` to hold onto failed messages and attempt to send them later once a connection is restored? Or is the exception the user should handle this exception based on business requirements?

**Comment by Nevon** [comment]
The latter. If we at any time start storing messages for later delivery, we get into hairy situations like what to do if the process crashes or if the machine suddenly dies - how would the user become aware that they lost data? We would also need a way for the user to enforce ordering, since if they produce two messages in a row, they'd expect the first one to come before the second one.

Not saying it's impossible, but it's a lot easier and cleaner to do this in userland code (or some small library that wraps `producer.send`), where you know the business requirements and have access to some external persistence.
