### ISSUE TITLE
producer.connect event not emitted after reconnect

### ISSUE THREAD

**Issue by robodude666** [tulios/kafkajs#629]
As a user, I would expect the `producer.connect` event would be emitted on a reconnection:

```js
producer.on('producer.connect', (e) => {
  console.log("connected", e)
})
```

However, it seems like it only gets emitted once during `await producer.connect()`. It would be good to either have a dedicated `producer.reconnected` event emitted, or add a `reconnected: true` to the `producer.connect` event.

The use case would be if my code detects a `KafkaJSNumberOfRetriesExceeded` it knows to buffer messages until a reconnect event is received.

A workaround would be to call:

```js
await producer.connect()
```
until it succeeds before sending any new messages, but this seems kludgy.

**Comment by Nevon** [comment]
I kind of regret emitting that event to begin with, as it's really confusing what it means and what to use it for.

The thing is, we emit that event the first time the producer manages to connect to one of the configured brokers. I.e. when `producer.connect()` resolves, as you mentioned. But that just tells you that we managed to connect to _a_ broker. To actually produce a message to a particular topic partition, you may need to connect to more brokers. So just because you got a `connected` event doesn't necessarily mean that everything will work. Throughout the lifetime of a producer, you may disconnect and connect to many different brokers over time.

> The use case would be if my code detects a KafkaJSNumberOfRetriesExceeded it knows to buffer messages until a reconnect event is received.

I don't think this is a good idea, because there are many things that can cause this issue, and being able to connect to a broker does not mean that producing will work.

**Comment by robodude666** [comment]
If that's the case, I'd be in favor of deprecating the connect/disconnect events. Or having them reworked. Perhaps the connect event for the consumer could include the broker it was connected to, or list of topics that are available to it?

> I don't think this is a good idea, because there are many things that can cause this issue, and being able to connect to a broker does not mean that producing will work.

What would you recommend then? If my service needs to publish an event, it'd have to buffer them on failure and attempt later; no?

**Comment by Nevon** [comment]
> What would you recommend then? If my service needs to publish an event, it'd have to buffer them on failure and attempt later; no?

That depends on your business requirements, of course, but you would approach it in the same way you'd approach any other type of delivery failure. Just catch the `producer.send` call and store the message somewhere for later processing (maybe in a DB or something). Same thing as if you failed to call an external API or something.
