### ISSUE TITLE
LEADER_NOT_AVAILABLE error

### ISSUE THREAD

**Issue by ramimoshe** [tulios/kafkajs#639]
hi

i am trying to fetch all topics from kafka server and i am getting this error 
Error code: "LEADER_NOT_AVAILABLE"
Message: "There is no leader for this topic-partition as we are in the middle of a leadership election"

it works from from kafka-pyhthon (https://kafka-python.readthedocs.io/en/master/usage.html) sdk and kafka cli

can you tell me what is wrong ?
* i am using kafka with ssl

here is my snippet code

```js
static createKafkaClient(brokers, certs) {
            return new KafkaClient({
                clientId: 'my-client',
                brokers : brokers,
                ssl     : {
                    ca  : certs.caroot,
                    key :certs.key,
                    cert:certs.certificate
                }
            });
    }

const kafkaAdminClient = createKafkaClient(bootstrap_servers, certs).admin();
yield kafkaAdminClient.connect();
const topics = yield kafkaAdminClient.fetchTopicMetadata(); // the exception came from here
yield kafkaAdminClient.disconnect();
```

**Comment by ramimoshe** [comment]
i found that the issue came with Kafka cluster with 2 broker (even),
when i am doing it with Kafka with 3 brokers it works

there is any issue regarding to even brokers?

**Comment by Nevon** [comment]
I don't believe that this is an issue with KafkaJS, but likely an issue with how your cluster is set up. Why it works with kafka-python and the kafka cli, I can't answer (you also didn't mention what exactly you did with those clients, so I don't know if it's equivalent to what you're doing with KafkaJS), but in order to get topic metadata we need to talk to the leader for that topic partition. If there is no leader, which the broker is telling you, there's nothing to do for the client except to wait.

In order to elect a leader, the cluster needs enough in-sync replicas to reach a quorum. Perhaps one of your brokers were not in sync, which meant a quorum could not be reached?
