### ISSUE TITLE
Why the consumer is taking too long to running? 

### ISSUE THREAD

**Issue by rqbazan** [tulios/kafkajs#701]
I've used [the example of consumer](https://github.com/tulios/kafkajs/blob/master/examples/consumer.js) to make some tests, and I've noticed that sometimes the consumer `run` method is taking too long. 🤔

```
connected
subscribed
{"level":"INFO","timestamp":"2020-04-18T00:29:33.383Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"test-group-1"}
{"level":"INFO","timestamp":"2020-04-18T00:29:55.982Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"test-group-1","memberId":"example-consumer-4911e4c3-6f7d-46bc-8556-4ba1fed7f279","leaderId":"example-consumer-4911e4c3-6f7d-46bc-8556-4ba1fed7f279","isLeader":true,"memberAssignment":{"tracking_topic":[0]},"groupProtocol":"RoundRobinAssigner","duration":22598}
running
```

This time the consumer takes `22598ms`, you could see it in the duration property of the second log. 😪

**Comment by goriunov** [comment]
@rqbazan most likely it is taking too long after you disconnect and connect consumer within short amount of time. From what i understand this happens due to kafka needed to remove old consumer and it depends on session timeout. I think default is set to 30s so if you disconnect consumer and reconnect it back it will take up to 30s to start to consume data.... (this is based on my observation). You can actually try to describe consume group to confirm that

**Comment by rqbazan** [comment]
@goriunov thanks for the answer, I've just noticed that I was interrupting the disconnect process killing the script before it happens. So, when I execute the script again the consumer group still has the previous consumer. 😄 Thanks again! 

**Conclusion:** don't interrupt to disconnect process before it finished otherwise the next time, the consumer run method will take some time.
