### ISSUE TITLE
Support delay consumer

### ISSUE THREAD

**Issue by chumanhquang** [tulios/kafkajs#725]
**Is your feature request related to a problem? Please describe.**
After send messages to Kafka, some messages have failed and I must to retry it after 'delay' ms.
I can to store it in a DB, and have a schedule to run. But i wonder if there's any way to consumer delay when retrieving a message?

I can do it by add a timestamp field to the message. And use setTimeout. But when delay is big enough (> sessionTimeout) can lead to consumerGroup rebalancing.
Sorry if there's anything wrong. Eng is not my native language.
Thankyou.

**Comment by Nevon** [comment]
I'm not sure I fully understand your question. Do you mean that you are failing to produce a message or that you are failing to consume already produced messages?

If it's the former (producer failing to send), I'm afraid that's on you to solve, as it's entirely outside the scope of KafkaJS. We already have retries internally, but if we exhaust those, you will have to decide whether to report an error or if you need to persist and re-send the messages later.

If it's the latter (consumer failing to process a message), a typical solution would be to use a dead-letter queue. [Uber has a good explanation of how it works](https://eng.uber.com/reliable-reprocessing/). The basic idea is to try to process your message, and if processing fails, you take the message, wrap it in another message with a `process_after` timestamp sometime in the future, and publish that to a second topic (your "dead-letter queue"). When you consume from the second topic, you first check "is it currently after `process_after`"), and if it is, you try to process the message, otherwise you wait a bit and try again.

There are other ways to implement dead letter queues, with multiple queues or counters rather than timers, but that's the general idea. There are quite a few writeups online regarding it, though personally I've found Uber's to be the best one so far.
