### ISSUE TITLE
autocommit false doesnt work for me

### ISSUE THREAD

**Issue by yuriabaev** [tulios/kafkajs#743]
scenario:
im setting autocommit false,
producing 12 messages 
consuming them.. (say from offset 100)
shutting down consumer 
start  a new consumer

in that stage, I expect to the 2nd consumer to read all messages again starting offset 100 (because no committing was done)

but when producing new messages I see that the 2nd consumer starts from the new offset (113) i.e the commit still occurs somehow.. 

what do I get wrong?

that is my consumer code
```
const { Kafka } = require('kafkajs');
const kafka = new Kafka({
  clientId: 'my-app',
  brokers: ['192.168.14.10:9095']
});
const admin = kafka.admin();
const consumer = kafka.consumer({ groupId: 'test-group' });
const run = async () => {
  // admin
  await admin.connect();
  // Consuming
  await consumer.connect();
  await consumer.subscribe({ topic: 'topic-test2'});
  await consumer.run({
    autoCommit: false,
    eachMessage: async ({ topic, partition, message }) => {
      console.log({
        partition,
        offset: message.offset,
        value: message.value.toString()
      });
      }
    }
  });
};
run().catch(console.error);
```

**Comment by Nevon** [comment]
When the consumer starts, it needs to know from which offset it should start consuming. If there are committed offsets for the consumer group, it will start from the last committed offset. If there are no committed offsets, it will either start from the start of the topic or from the end of the topic. This is controlled using the `fromBeginning` flag in `consumer.subscribe`:

```js
// Will start from the earliest offset
await consumer.subscribe({ topic: 'topic-1', fromBeginning: true })

// Will start from the last offset
await consumer.subscribe({ topic: 'topic-2', fromBeginning: false })

// By default it will start from the last offset
await consumer.subscribe({ topic: 'topic-3' })
``` 

Since you are not setting `fromBeginning` to anything, it's defaulting to `false`, thus starting from the end of the topic.

This is documented here: https://kafka.js.org/docs/consuming#a-name-from-beginning-a-frombeginning
