### ISSUE TITLE
[question] autoCommitInterval,autoCommitThreshold only work once

### ISSUE THREAD

**Issue by Kijin-Seija** [tulios/kafkajs#759]
My code:

index
```javascript
const receiver = require('./receiver')
async function init() {
  await producer.connect();
  await consumer.connect();
  await consumer.subscribe({ topic: config.topic });
  await consumer.run(receiver);
}

async function send(msgs) {
  await producer.send({
    topic: config.topic,
    messages: msgs
  });
}

// I will run send() if someone post a http request to server
```
receiver.js
```javascript
module.exports = {
  autoCommit: true,
  eachMessage: async ({ message }) => {
    try {
      await dataModel.addData([JSON.parse(message.value.toString())]);
      console.log(JSON.parse(message.value.toString()))
    } catch (e) {
      console.error(e.message);
      throw e;
    }
  },
  autoCommitThreshold: 5
  // autoCommitInterval: 10000
};
```

when I start the server, at first 5 message, it works well as I thought. It will commit once after 5th message pushed. But when I send 6th, 7th, ... message, the consumer commits immediately after each message  pushed.

when I use ```autoCommitInterval```, it's the same, only first 10s, the consumer will wait for all messages, then it commit every message immediately.

Can anyone help?

**Comment by Nevon** [comment]
I'm not sure if I would say that this is a bug or not, but it's definitely not intuitive.

When we created `autoCommit`, we intended for it to allow you to commit several times during the processing of a single batch. For example, let's say you get 950 messages in a batch, you might want to commit every 100 messages, so that you don't have to throw away a bunch of work if something goes wrong on message 949.

However, at the end of the batch, we still wanted to commit the remaining work, so the second to last thing we do in each iteration of the fetch loop is to call `autoCommitOffsets`, which will commit all resolved offsets if `autoCommit` is true, regardless of `autoCommitThreshold`/`autoCommitInterval`.

In the case above, it means that for a batch of 950 messages and a `autoCommitThreshold` of 100, we would make 10 commits: 100, 200, 300 ... 950. So the last commit would be just for the messages between 900 and 950 (i.e. less than `autoCommitThreshold`).

What's happening in your case is that you have so few messages that your batch just contains a single message, so even though you have an `autoCommitThreshold` of 5, at the end of the batch we'll still commit that 1 offset.

---

I'm not really sure that we need to call `autoCommitOffsets` at the end of the fetch loop. We will still use resolved offsets when fetching the next batch, so it's fine if it doesn't get committed until the next batch.

One problem I do see is what happens when you reach the head of the topic. Again, let's say you have an `autoCommitThreshold` of 100, but now we've changed so that we don't commit all remaining offsets at the end of the fetch loop (i.e. we completely respect `autoCommitThreshold`). In our example, we would commit offset 900, then process the remaining 50 messages, but we won't actually commit them until 50 more messages have been produced, since you asked us to only commit every 100 messages. If you shut down your consumer, you'll have to re-process those 50 messages, and there's no guarantee that you will ever commit them unless someone produces more to the topic.

The more I think about it, the more I think it's a footgun. If you _really_, _really_ don't want to commit until you've processed 5 messages, disable `autoCommit` entirely and commit manually. That's a pretty advanced use-case with plenty of rope to hang yourself, so I don't recommend it, but it's possible: https://kafka.js.org/docs/consuming#a-name-manual-commits-a-manual-committing
