### ISSUE TITLE
Kafka url config is not honored

### ISSUE THREAD

**Issue by tzachshabtay** [tulios/kafkajs#769]
**Describe the bug**

Configuring kafka with a custom url (not `localhost:9092`):
```typescript
const kafka = new Kafka({
	clientId: 'my-id',
	brokers: [KAFKA_URL]
})

const admin = kafka.admin()
```

When I run `await admin.connect()` it works fine (and I verified that if I give a wrong url it fails here).
However when I run `await admin.fetchTopicMetadata(undefined as any)` I get this error:
```
{"level":"ERROR","timestamp":"2020-06-17T04:10:33.960Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 127.0.0.1:9092","broker":"127.0.0.1:9092","clientId":"krowser","stack":"Error: connect ECONNREFUSED 127.0.0.1:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)"}
```
You can see in the error message that the url is `127.0.0.1:9092` and not the one I configured.

**To Reproduce**
You can reproduce with my application here: https://github.com/tzachshabtay/krowser

Steps:
1. clone the repo
2. run `npm i`
3. run `npm run build:backend`
4. run `npm run build:frontend`
5. In `test/docker-compose-single-broker.yml`  change the exposed port to 9093 instead of 9092. I.e change this line:
https://github.com/tzachshabtay/krowser/blob/0de0d03c722b8e8906583edd82af56c74af47446/test/docker-compose-single-broker.yml#L23 to be `- "9093:9092"`
6. run `npm run kafka-up` to start kafka with the 9093 port (and also schema-registry and zookeeper), wait a few minutes for kafka to boot
7. run `export KAFKA_URL=localhost:9093` (this tells my application to configure kafkajs with this url)
8. run `npm start` to start the application. This should work (and this calls `admin.connect`) 
9. In the browser go to `localhost:9999` (this calls `fetchTopicMetadata`). Then observe the logs on the server to see the errors.

**Expected behavior**
Calling `admin.fetchTopicMetadata` should use the same kafka url config that I assigned it (and the same url used by `admin.connect`)

**Observed behavior**
Calling `admin.fetchTopicMetadata` ignored my url config and used `127.0.0.1:9092`.

**Environment:**
 - OS: Mac OS Moave 10.14.4
 - KafkaJS version: 1.13.0-beta.4
 - Kafka version: 5.2.1
 - NodeJS version: 12.13.0

**Comment by Nevon** [comment]
This is not a bug in KafkaJS, but rather a misconfiguration of your Kafka broker. See https://github.com/tzachshabtay/krowser/blob/0de0d03c722b8e8906583edd82af56c74af47446/test/docker-compose-single-broker.yml#L25

`KAFKA_ADVERTISED_LISTENERS` is defining what address and port your Kafka broker is "advertising itself" as listening on. Meaning, if you ask your broker: "Hey, what's the address to the current controller broker?" it will respond with the advertised listener address & port. In your case, that's `LISTENER_DOCKER_EXTERNAL`, which is `${DOCKER_HOST_IP:-127.0.0.1}:9092`. So what's happening is that on initial connect, we connect to whatever address you gave us in the brokers array, which is correctly pointing to the exposed port of your docker container, but then that broker will return another address, which is the `LISTENER_DOCKER_EXTERNAL` address, which is incorrectly configured to use port `9092`.

If you just change the `LISTENER_DOCKER_EXTERNAL` address to use port 9093, it should work just fine.

**Comment by tzachshabtay** [comment]
@Nevon if I change `LISTENER_DOCKER_EXTERNAL` to be `${DOCKER_HOST_IP:-127.0.0.1}:9093`, then I get an error on `admin.connect`:

```
{"level":"ERROR","timestamp":"2020-06-17T16:18:27.153Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Closed connection","retryCount":0,"retryTime":308}
```

**Comment by Nevon** [comment]
Sorry, I must have misread the configuration in my haste. Regardless, this is simply a misconfiguration of Kafka itself. As I explained, the address that you specify in the `brokers` array is just used for the initial connection. Once the initial connection as been established, the broker will give us whatever the address is for the other brokers in the cluster, by using the `KAFKA_ADVERTISED_LISTENERS` configuration.

Your initial connection works because you are correctly pointing to your container on the correct port. However, when you call `fetchTopicMetadata` we ask the broker who is the current controller, and it gives us back an address which does not point to the correct container. From what you are saying, it is telling you to connect to `127.0.0.1:9092`, which as you can see in your config is the default you have set in case the environment variable `DOCKER_HOST_IP` is unset.

Robin Moffat from Confluent explains this in this article: https://rmoff.net/2018/08/02/kafka-listeners-explained/ I recommend that you read through it.
