### ISSUE TITLE
Slower connection time with many large topics

### ISSUE THREAD

**Issue by cpiemontese** [tulios/kafkajs#819]
Hi, recently I've noticed a correlation between the number of topics and the time it takes a consumer to start processing messages. 
This could also be influenced by the number of messages on those topics and how many partitions they have, but I don't have definitive proof.

This problem first emerged when I tried to connect a consumer to ~30 topics with varied numbers of partitions (a minimum of 1 and a maximum of 12). The consumer took such a long time that it exceeded the `sessionTimeout` and could never manage to join its consumer group.
One way to solve this was increase `sessionTimeout` and `rebalanceTimeout` substantially.
My understanding is that this happens because the consumer doesn't send an heartbeat until after it processed at least a message.

Is this physiological to having such a high number of topics or is there a way to get around having to set large timeouts?

**Comment by Nevon** [comment]
I don't think I would call it pathological to subscribe to 30 topics with a single consumer instance, but it is certainly unusual. More commonly, you would create a consumer instance per topic, or at least per group of related topics. For example, the following wouldn't be recommended:

```js
const consumer = kafka.consumer({ ... })

await consumer.connect()
const topics = [
  'order-events',
  'refund-events',
  'user-communication-events'
]

await Promise.all(topics.map(topic => consumer.subscribe({ topic })))

await consumer.run({
  eachMessage: async ({ topic, message }) => {
    switch (topic) {
      case 'order-events':
        return processOrderEvent(message)
      case 'refund-events':
        return processRefundEvent(message)
      case 'user-communication-events':
        return processUserCommunicationEvent(message)
    }
  }
})
```

In this case, there is nothing to be gained by them sharing a single consumer, because messages from the different topics don't need to be joined and they really have no relationship to each other. In this case, it would be much better to have three consumer instances and just subscribe one instance to one topic.

```js
const consumers = [
  { topics: ['user-communication-events'], consumer: kafka.consumer({ ... }), eachMessage: async () => {} },

  // Maybe these two topics actually need to be consumed together for some reason
  { topics: ['order-events', 'refund-events'], consumer: kafka.consumer({ ... }), eachMessage: async () => {} }
]

await Promise.all(consumers.map(({ topics, consumer, eachMessage }) => {
  await consumer.connect()
  await Promise.all(topics.map(topic => consumer.subscribe({ topic })))
  consumer.run({ eachMessage })
}))
```

If you have 30 topics that are actually relevant to consume with the same consumer, that _should_ still work. In Kafka, we work with partitions, so what happens is that we get all the partitions for all your subscribed topics and we map those to the brokers to create fetch requests towards each broker that is a leader for one or more partitions. So let's say that you have 30 topics with an average of 9 partitions spread across 6 brokers. Assuming that the partitions are balanced evenly across the brokers, we would make 6 requests, with each request asking for data for 45 partitions.

Now, in v1.12.0 of KafkaJS, you will always end up waiting for the slowest response before starting to process messages, which is probably where your issue is. If one request ends up taking a long time, your consumer won't have an opportunity to heartbeat and it will get kicked out of the consumer group. In the pre-release version of KafkaJS, this works differently, as we start to process messages as soon as we get a response for any of the requests. You still end up waiting for the slowest response before starting the fetch loop over again, but at least you were able to do work while waiting.

You could [try the pre-release version](https://www.npmjs.com/package/kafkajs/v/beta) and see if that changes anything. But I would also encourage you to consider if subscribing to 30 topics from a single consumer instance actually makes sense for your use-case, as I would say it's quite unusual.

Could you share some numbers for us, like how many brokers you have, what your `maxBytes`, `minBytes` and `maxBytesPerPartition` are set to, and how long the request durations are for the consumer (you can [get this from the `consumer.events.REQUEST` instrumentation events](https://kafka.js.org/docs/instrumentation-events#a-name-consumer-a-consumer))

**Comment by cpiemontese** [comment]
Thank you very much for the detailed response.

I understand that subscribing to that many topic with just one consumer is a bit unusual, but our use case requires that messages from all topics are processed with the same logic so I think it's legitimate enough.
I think the change coming in the pre-release version could indeed help. Is there an ETA on when the v1.13.0 will be released? 
We are using KafkaJS in production and it's unclear how stable/unstable the beta version is.

We have one broker and `maxBytes`, `minBytes` and `maxBytesPerPartition` are all set to their default values. As to how long the request durations are, I don't have that kind of data right now since this use case emerges from time to time with high bursts of data and I wasn't prepared to measure it. I'll try to gather it next time.

**Comment by Nevon** [comment]
> We have one broker and maxBytes, minBytes and maxBytesPerPartition are all set to their default values. As to how long the request durations are, I don't have that kind of data right now since this use case emerges from time to time with high bursts of data and I wasn't prepared to measure it.

Hmm, then it is very strange that you're having issues. If you are requesting data for 180 or so partitions from a single broker, you will just be making a single fetch request per iteration of the fetch loop. Since the amount of data you'll get back is bounded by `maxBytes`/`maxBytesPerPartition`, you'll get a maximum of 10mb back. Using the beta version of KafkaJS shouldn't really make a difference in that case.

I gotta write a test to see what happens if I subscribe to 30 topics with 6 partitions each and try to consume. I don't see any conceptual reason why it wouldn't work.

**Comment by cpiemontese** [comment]
Sorry, I checked and we actually have 9 brokers. I was thinking about the Bootstrap server (whose address is passed as `brokers`).

**Comment by Nevon** [comment]
Okay, so I wrote my test now. In my case, I had 30 topics with 6 partitions each, divided over 3 brokers. The brokers were running locally.

First I produced a few million messages to all topics, distributed more or less evenly across all partitions. Then I started a regular `eachMessage`-using consumer with all default settings, subscribed to all topics and starting from the beginning of the topics. Running that was no problem. It was chugging through just fine.

Then I added a listener for the request instrumentation event that just logged the api name, the request duration, the time the request spent waiting in the queue (in case it was being throttled) and the size of the payload in bytes. I expected the request duration to be quite low, since I'm not actually going over the internet:

```
SaslHandshake request took 2ms. Pending for 1ms. Size 47 bytes.
SaslAuthenticate request took 2ms. Pending for 0ms. Size 20 bytes.
GroupCoordinator request took 2ms. Pending for 0ms. Size 35 bytes.
SaslHandshake request took 1ms. Pending for 0ms. Size 47 bytes.
SaslAuthenticate request took 2ms. Pending for 0ms. Size 20 bytes.
JoinGroup request took 5ms. Pending for 0ms. Size 657 bytes.
Metadata request took 8ms. Pending for 0ms. Size 6157 bytes.
SyncGroup request took 11ms. Pending for 0ms. Size 1304 bytes.
OffsetFetch request took 4ms. Pending for 0ms. Size 3454 bytes.
ListOffsets request took 4ms. Pending for 0ms. Size 1892 bytes.
ListOffsets request took 7ms. Pending for 0ms. Size 1892 bytes.
ListOffsets request took 9ms. Pending for 0ms. Size 1892 bytes.
Fetch request took 905ms. Pending for 0ms. Size 10488618 bytes.
Fetch request took 2681ms. Pending for 0ms. Size 10488618 bytes.
Heartbeat request took 11ms. Pending for 0ms. Size 10 bytes.
Fetch request took 4348ms. Pending for 1ms. Size 10488618 bytes.
OffsetCommit request took 8ms. Pending for 0ms. Size 282 bytes.
Fetch request took 1455ms. Pending for 0ms. Size 10488618 bytes.
Fetch request took 3488ms. Pending for 0ms. Size 10488618 bytes.
Fetch request took 5347ms. Pending for 0ms. Size 10488618 bytes.
Heartbeat request took 2683ms. Pending for 0ms. Size 10 bytes.
OffsetCommit request took 6ms. Pending for 0ms. Size 36 bytes.
LeaveGroup request took 6ms. Pending for 0ms. Size 10 bytes.
```

As you can see, even running locally each fetch request took a few seconds, since it's schlepping 10mb for each broker (30mb in my case). If we added network latency to this we would see these numbers go up quite a bit.

> Sorry, I checked and we actually have 9 brokers. I was thinking about the Bootstrap server (whose address is passed as brokers).

So in your case you'll be making 9 requests for 10mb each. Maybe try lowering `maxBytes` to something significantly smaller, like a megabyte or two, and I bet you won't be having the same issue. Although being on v1.12.0 you'll still suffer having to wait for the slowest response before processing.

**Comment by cpiemontese** [comment]
Hi!

We managed to test again, this time using the beta version as you suggested and everything went smoothly. We are now running it in production as it seems stable.
While I agree that lowering `maxBytes` could solve the issue, it seems like a less appealing solution if the library can handle that kind of load.
Is there an ETA on when the v1.13.0 will be released?

Again, thank you very much for your support :smiley:

**Comment by Nevon** [comment]
> Is there an ETA on when the v1.13.0 will be released?

I'm afraid not, as we currently don't have a good way to validate release stability beyond the pipeline. See #736.
