### ISSUE TITLE
Runner is not awaiting scheduleFetch

### ISSUE THREAD

**Issue by katerina-semikina** [tulios/kafkajs#829]
**Describe the bug**
scheduleFetch method in runner->start returns Promise, but there is no await.
In runner.js file,  on [line 125](https://github.com/tulios/kafkajs/blob/master/src/consumer/runner.js#L125) it should contain `await`:
```
await this.scheduleFetch()
```
Please, confirm whether this is a bug from your perspective, then I'll create a PR for this fix.

**To Reproduce**
Create a couple of consumer groups with fromBeginning = false.
Run the consumer and then send a message to the topic using producer. Repeat for each consumer group.

**Expected behavior**
Consumer receives the message sent after the consumer was run.

**Observed behavior**
Some consumers randomly don't receive the message at all.

**Environment:**
 - KafkaJS version 1.12.0
 - NodeJS version 14.2.0

**Additional context**
Related to fix: https://github.com/tulios/kafkajs/pull/752

**Comment by Nevon** [comment]
Not awaiting `scheduleFetch` there is intentional, as we don't want to wait for the entire fetch loop to run before resolving `consumer.run`. Typically `consumer.run` is invoked during service startup, but an iteration of the fetch loop could take minutes in some cases (large batches with slow processing). Even if there's no explicit contract that says that `consumer.run` will resolve "quickly", changing that behavior would likely impact production workloads due to the implicit assumption that it will resolve as soon as the consumer has joined the consumer group.

The bug that you describe, however, is interesting. If you produce a message right after `consumer.run` resolves, it's very possible that that consumer may not receive that message. In fact, this was an issue in our tests until we started using `fromBeginning: true` everywhere.

I have 2 thoughts:

1. The only case where this makes sense is if you are running a consumer and producer in the same process and the consumer is consuming from the topic that the producer is producing to. If the consumer and producer are running in different processes or on different hosts, you can forget about that synchronization. This seems like an exceedingly rare circumstance to me.
2. I _think_ a workaround would be to listen for the consumer `FETCH` event to know that the fetch has happened, after which it should be safe to produce. Something like:

```js
const waitForFetch = (consumer, timeout) => new Promise((resolve, reject) => {
  const timeoutId = setTimeout(() => {
    reject(new Error(`Timed out after ${timeout}ms waiting for consumer to fetch`))
  }, timeout)

  const { FETCH } = consumer.events
  const removeListener = consumer.on(FETCH, () => {
    clearTimeout(timeoutId)
    removeListener()
    resolve()
  })
})

const consumerReady = waitForFetch(consumer, 60000)
await consumer.run({ ... })
await consumerReady

await producer.send(...)
```

I'm not 100% sure about this without testing it. What I would be concerned about would be that on the first batch, if there aren't any messages to process, I'm not sure that we would resolve any offset, so we might start from the same "latest offset" on the next fetch.

**Comment by katerina-semikina** [comment]
@Nevon Thanks for the explanation. Finally I decided to avoid using this approach (it was used in tests in order to have multiple consumers and be able to set different message handlers). I just wonder if `this.scheduleFetch` actually waits for an iteration of fetch loop or does it just schedule?

**Comment by Nevon** [comment]
> I just wonder if this.scheduleFetch actually waits for an iteration of fetch loop or does it just schedule?

`scheduleFetch` _is_ the fetch loop. It awaits `fetch` before scheduling the next iteration of itself:

https://github.com/tulios/kafkajs/blob/828b6fbf4d55f3708f58286ce8c03be0e8fdf333/src/consumer/runner.js#L408-L410
