### ISSUE TITLE
Consumer receiving topic metadata without being subscribed

### ISSUE THREAD

**Issue by Nevon** [tulios/kafkajs#83]
We saw this behavior when a service was re-using the same group id as a different service. They were getting metadata for a completely different topic than the one they were subscribed to, causing KafkaJS to crash the consumer when trying to find the leader for a partition: `Cannot read property ‘partitionMetadata’ of undefined`.

I.e.
1. Service A with group id `consumer` subscribes to `topic-1` and consumes messages.
2. Service B with group id `consumer` subscribes to `topic-2` and tries to consume messages.
2. Service B consumer crashes because it only gets topic metadata for `topic-1`.

**Comment by tulios** [comment]
I gave some thought to this problem, and I think the consumers should ignore topics that they don't know (are not subscribed). The reason is that when update consumers, let's say a rolling update; They might subscribe to new topics or stop listening to old ones. The leader of the group will determine which data the other consumers will receive, thus potentially receiving more or fewer topics then originally until the end of the update.

So, I think we should be resilient to this case but warn whenever it happens. WDYT?

**Comment by tulios** [comment]
Wow, that's weird. We have to investigate.

**Comment by tulios** [comment]
@Nevon should we close this for now?
