### ISSUE TITLE
Consuming without group id

### ISSUE THREAD

**Issue by ronfarkash** [tulios/kafkajs#853]
Hey I want to be able to consume using KafkaJS without specifying the consumer's group id.

I found out that in Kafka Python I can turn off auto commit for the consumer without giving it a group id and it allows me to consume while manipulating the offset.
Is it possible to do it in KafkaJS?  and if not would it be possible?

**Comment by xamgore** [comment]
Have the same question.

**Comment by patrykwegrzyn** [comment]
I can see this beneficial for streamings apps where something like ktable is needed, right now i have to create a lot of junk group ids(random) in order to scale on k8s.  Consuming without group id would be very beneficial in use cases like this

**Comment by Nevon** [comment]
It's not possible at this time. KafkaJS was built around the concept of consumer groups, rather than manual assignment. Committing offsets is strictly optional, as you can turn off `autoCommit`, use `resolveOffset` and/or `seek` to manipulate the offset, and then store your offsets outside of Kafka, but it's not particularly ergonomic.

That said, it is of course possible to enable the use-case, but I suspect it would be a rather large undertaking. I think it is highly related to #373, which doesn't currently seem to have a sponsor. I'd be happy to discuss a proposal for how to make it happen, what the API might look like and what the implications would be.

I'm going to close this issue in favor of #373. Feel free to continue the discussion there.
