### ISSUE TITLE
Cant re-use consumer group

### ISSUE THREAD

**Issue by danielsinai** [tulios/kafkajs#870]
Hi, I am trying to use the same consumer group for different topics and applications and I am getting "not available topic partitions".

I saw in the FAQ that kafkajs does not supoort it although its nativly available, is it possible to understand why kafkajs does not support it? And maybe implement it? 

Thanks alot!

**Comment by Nevon** [comment]
That's not supported because that's not how Kafka works. The whole point of consumer groups is that they allocate work across several identical consumers. If you want to consume different topics, then by definition you don't want them to be part of the same consumer group.

Perhaps what you are talking about is manual assignment, which is not supported by KafkaJS and is not really something we are looking to support (at least there's no work ongoing to support it). Consumer groups were added to Kafka sometime around 2016 and is meant to replace manual assignment in the vast majority of cases.

You can read up on consumer groups vs manual assignment here: https://dzone.com/articles/dont-use-apache-kafka-consumer-groups-the-wrong-wa#:~:text=In%20Apache%20Kafka%2C%20the%20consumer,the%20members%20of%20the%20group. Note that it's referring to the Java client, but the concepts are the same.

**Comment by danielsinai** [comment]
Hi sorry for the delay, you may be right but we have some special use case for this one.

Anyway, thank you!
