### ISSUE TITLE
Event names error check shows incorrect message

### ISSUE THREAD

**Issue by crobinson42** [tulios/kafkajs#889]
**Describe the bug**
When using `producer.on('producer.events.disconnect', cb => { ... })` the error message says the event doesn't exist and to use one of the following events:

![image](https://user-images.githubusercontent.com/5973579/94203827-fe0abf00-fe74-11ea-9829-3f9303b379d3.png)

The issue is here:

```js
// producer/index.js

...

const { values, keys } = Object
const eventNames = values(events)
const eventKeys = keys(events)
  .map(key => `producer.events.${key}`)
  .join(', ')

...

const on = (eventName, listener) => {
    if (!eventNames.includes(eventName)) {
      throw new KafkaJSNonRetriableError(`Event name should be one of ${eventKeys}`)
    }
...

**Comment by Nevon** [comment]
This was actually intentional, but I see the confusion. Basically, we want to encourage people to use the enums provided on the client instance rather than just using random strings, which is why when you subscribe with an invalid event we include the enum key in the error message, not the value. The intention is to make you subscribe with `producer.events.DISCONNECT`, not the literal value `"producer.events.DISCONNECT"`.

Maybe there's a way to make the error message clearer instead. Maybe `Valid events are members of "producer.events": ${eventKeys}`?

**Comment by crobinson42** [comment]
@Nevon how about the vents are exported from the package so constants can be used when subscribing instead of string literals?

**Comment by Nevon** [comment]
I'm not sure I follow. You can use the constants when subscribing. That's what we try to encourage:

```js
const producer = kafka.producer()
producer.on(producer.events.DISCONNECT, () => {
  producer.logger().warn('Producer disconnected')
})
```

**Comment by crobinson42** [comment]
Ohhh! ☝🏼 🤦🏽‍♂️ I overlooked that.

What I was referring to before you pasted the constants was the package exporting something like `const { events } = require('kafka-js')` so it could be referenced like this `producer.on(events.producer.DISCONNECT, ...`.

Anyhow, now I understand the error that was spit out in the console when it said _must be one of "producer.events.*_.

Thanks and sorry for the disruption - I thought I was helping 😑

**Comment by Nevon** [comment]
> Thanks and sorry for the disruption - I thought I was helping 😑

It's all good! Thanks for taking the time to get involved regardless!
