### ISSUE TITLE
KafkaJSProtocolError INVALID_TXN_STATE error: Do we need explicit producer connect call for transactions?

### ISSUE THREAD

**Issue by sureshballa** [tulios/kafkajs#893]
We are using transactions to produce messages to Kafka (based on code mentioned in documentation and also pasted here for reference  and all was working fine with no issues. But off-late we are seeing this error.

```
{"name":"KafkaJSProtocolError","retriable":false,"type":"INVALID_TXN_STATE","code":48}
{"level":"ERROR","timestamp":"2020-09-27T11:58:18.753Z","logger":"kafkajs","message":"[Connection] Response EndTxn(key: 26, version: 0)","broker":"^^^^","clientId":"@#$%","error":"The producer attempted a transactional operation in an invalid state","correlationId":4,"size":10}
````

**Code that producer generated the error INVALID_TXN_STATE**

```js
const transaction = await producer.transaction()

try {
  await transaction.send({ topic, messages })

  await transaction.commit()
} catch (e) {
  await transaction.abort()
}
```

We tried some trail and error and found below code fixes issue (notice explicit call to connect and disconnect)

**Code that producer DID NOT generate the error INVALID_TXN_STATE**

```js
producer.connect()
const transaction = await producer.transaction()

try {
  await transaction.send({ topic, messages })

  await transaction.commit()
  producer.disconnect()
} catch (e) {
  await transaction.abort()
}
```

Because I couldn't find API documentation for KafkaJS (all I could see is samples in documentation), I am not able to find root cause of original issue INVALID_TXN_STATE. I am left with below questions
1) In the first place, why I didn't get the error initially and why off-late I am seeing this issue
2) What is the purpose of explicit connect and disconnect call? Why documentation has explicit call for simple message producer but not for transaction based message producer.

Would appreciate if anyone can help me in answering these questions.

**Environment:**
 - OS: docker container and Mac
 - KafkaJS version: 1.12.0
 - Kafka version: 2.3.1
 - NodeJS version: 10.21.0

**Comment by sureshballa** [comment]
@tulios @Nevon Your inputs are very much appreciated. We are looking for some help here. We are close to moving our services to production, hence the request.

**Comment by sureshballa** [comment]
Detailed log (after enabling debug level logging to KafkaJS) is here - https://gist.github.com/sureshballa/9200da1f8c4025ea635400f06454d648

transaction.send method is throwing the error

**Comment by sureshballa** [comment]
Another observation - if we have a call to connect method once during bootstrapping of service, this issue is no more occurring.

So to summarise, to fix this issue, both the below options are working:

1. connect call on event message produce
2. connect call on bootstrapping of service

By the way, like I said before, this error is intermittent and not occurring in few of our services, where we do not have any connect call at all.

**Comment by sureshballa** [comment]
Hi @tulios @Nevon please let me know if my query doesn't make any sense, I see other issues are being ackowledged and getting inputs from you guys.

**Comment by Nevon** [comment]
You should definitely call `producer.connect` before initiating transactions and trying to produce messages. During service startup is an excellent opportunity for this. Note that both `connect` and `disconnect` return promises, so you should await them.

The producer itself has some mechanisms for reconnecting if the connection is lost, which maybe could make it work even if you haven't explicitly connected the producer, but it's not designed for lazy connections and if it does work it's not something we guarantee. The way to use it is to first connect explicitly.

You should not connect on every message produce. At best, it's a no-op, and at worst (if you've disconnected the producer) you have to go through a connection phase, protocol negotiation and authorization in between every message, which would absolutely tank performance.

This would be a simple example showing how to use the producer in a transactional manner:

```js
const client = new Kafka({ clientId, brokers })
const producer = client.producer({
  maxInFlightRequests: 1,
  idempotent: true,
  transactionalId: `my-transactional-id` // https://github.com/tulios/kafkajs/pull/902
})

const start = async () => {
  // Connect during startup
  await producer.connect()

  return producer
}

const produce = async producer => {
  // Use the same producer instance multiple times if you want
  const transaction = await producer.transaction()

  try {
    await transaction.send({ topic, messages })
    await transaction.commit()
  } catch (e) {
    await transaction.abort()
  }
}

const shutdown = async error => {
  if (error != null) {
    console.error(error)
  }
  
  // We disconnect the producer when shutting down
  await producer.disconnect()
}

start()
  .then(produce)
  .then(shutdown)
  .catch(shutdown)
```

> Why documentation has explicit call for simple message producer but not for transaction based message producer.

Either it's a simple oversight or whoever wrote that documentation decided to try to simplify the examples as much as possible to focus on the important parts, which are configuring the producer and working with transactions. The assumption is that if the user is learning about transactions, they already know the basics.

> In the first place, why I didn't get the error initially and why off-late I am seeing this issue

There are several possibilities.

1. The producer was not configured correctly. For example, if you don't have `maxInFlightRequests: 1`, you could get into invalid transaction states due to requests being processed in the wrong order. This could happen intermittently.
2. There has been some change in your implementation between then and now.
3. Since you're not awaiting the connect call (or not making it in the first place), there is some race condition happening.

**Comment by sureshballa** [comment]
thanks @Nevon for your inputs.
