### ISSUE TITLE
Stop batch processing during rebalancing

### ISSUE THREAD

**Issue by hovoodd** [tulios/kafkajs#916]
Hello! Is it possible to stop batch processing during rebalancing? Otherwise, after rebalancing the partition can be assigned to another consumer and it will start processing the same batch, because previous consumer will not be able to commit the offset.

**Comment by Nevon** [comment]
This is a distributed system, so you first need to **know** that there is a rebalance in process. The way that we find out about that is because we try to do something on behalf of the consumer group, such as committing an offset or heartbeating, and get an error back telling us that we need to re-join the group.

In your scenario, if the partition gets re-assigned to another member of the group, the member that previously had it would get an error when it tries to commit or heartbeat, so it will discard the current batch, rejoin the group and be assigned new partitions. There's no way to stop processing when the group needs to rebalance before even finding out that it needs to.

**Comment by hovoodd** [comment]
> get an error when it tries to commit or **heartbeat**

This is great, because the heartbeat is sent after each message. Thank you!

**Comment by hovoodd** [comment]
btw, I was looking for a kind of `onRebalance` event handler in [`node-kafka`](https://www.npmjs.com/package/kafka-node#consumergroupoptions-topics):

```js
{
  // Callback to allow consumers with autoCommit false a chance to commit before a rebalance finishes
  // isAlreadyMember will be false on the first connection, and true on rebalances triggered after that
  onRebalance: (isAlreadyMember, callback) => { callback(); } // or null
};
```

**Comment by Nevon** [comment]
> Callback to allow consumers with autoCommit false a chance to commit before a rebalance finishes

Hmm, this is a good point, actually. Now that I think about it, I think my previous comment is half-right:

>  The way that we find out about that is because we try to do something on behalf of the consumer group, such as committing an offset or heartbeating [...]

I'm pretty sure that it's on the heartbeat that we find out that we need to re-join, _not on commit_. Because the consumer can still commit as long as it hasn't been kicked out of the group and it hasn't yet tried to re-join the group. Once it issues the JoinGroup request it can definitely not commit anymore until all the members have joined and synced.

By default, we heartbeat in between each message when using `eachMessage` and in between each batch with `eachBatch`. With `autoCommit: true`, this is handled already since we commit any resolved offset if there's an error, but with `autoCommit: false` it gets trickier. We do pass `heartbeat` to `eachBatch`, so the user _could_ catch the error and figure out if it's because the group is rebalancing, and then commit the resolved offsets before re-throwing the error, but that seems error prone and complicated for the user.

**Comment by t-d-d** [comment]
> so the user could catch the error ... and then commit the resolved offsets
I have been doing it like this.  But I agree an explicit callback would be cleaner.  And if we have that then it would make sense to have a callback for when partitions are assigned as well (although the instrumentation event suffices for me here.)
Java client callbacks https://kafka.apache.org/25/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html
