### ISSUE TITLE
Version support matrix

### ISSUE THREAD

**Issue by evanshortiss** [tulios/kafkajs#925]
**Is your feature request related to a problem? Please describe.**

This is a documentation request. No problems to report 😄 

**Describe the solution you'd like**

Libraries such as [kafka-python](https://kafka-python.readthedocs.io/en/master/compatibility.html) have clearly listed Kafka compatibility on their docs. It would be great if https://kafka.js.org/ did this too.

**Additional context**

It appears as though the various docker-compose files in this repo provide the necessary information and verification for version support, so this might be a quick win?

**Comment by Nevon** [comment]
From the README:

> It is compatible with Kafka 0.10+ and offers native support for 0.11 features.

Not sure if it's on the website anywhere though.

It's a little tricky to explain version support when it comes to Kafka. 0.10 is the oldest version that we support, but since the protocol is versioned, we will likely support any future version of Kafka as well. However, newer Kafka versions add new features that we may not support - but whether we support them or not doesn't really have anything to do with supporting the version of Kafka itself.

My only fear with explicitly stating that we support for example Kafka 2.4 is that people will then expect us to support every feature that's in 2.4, which is probably not the case.

**Comment by evanshortiss** [comment]
> However, newer Kafka versions add new features that we may not support 

You mean certain KIPs may not be implemented in this module, so it wouldn't be entirely accurate to state specific version supports?

If so, then I understand the rationale in not stating explicitly listing Kafka versions 👍

**Comment by Nevon** [comment]
> You mean certain KIPs may not be implemented in this module, so it wouldn't be entirely accurate to state specific version supports?

Yes, exactly. A KIP that makes it into Kafka 2.X may or may not make it into KafkaJS, depending on whether or not we have to make some change on the client side, but KafkaJS is still compatible with Kafka 2.X.
