### ISSUE TITLE
Allow sharing of `Cluster`/`BrokerPool` instances with multiple consumers

### ISSUE THREAD

**Issue by ankon** [tulios/kafkajs#961]
**Is your feature request related to a problem? Please describe.**

KafkaJS creates a lot of connections when one uses a lot of consumers[1], which may explain throttling issues seen with Confluent Cloud (#931) and also issues I have seen and so far ignored with smaller AWS MSK clusters.

Looking through the Kafka protocol and the code it should be possible to multiplex multiple consumers onto the same connection, at the (likely) cost of latency.

[1] or producers, or admin clients -- but this issue is specifically about the consumers :)

**Describe the solution you'd like**

For advanced users I would like to be able to create a single `Cluster`, and then hand it to the `consumer` method. The `consumer` method would check whether the cluster is "compatible" with the settings otherwise given to it that affect the connection (such as max requests in flight), and if these settings are compatible would use this cluster rather than create a new one when needed.

Methods for connecting/disconnecting may potentially be disabled on the returned consumer, in favor of having to control that explicitly on the shared cluster.

**Comment by ankon** [comment]
I'm probably going to try this out over the week, but instead of doing and then filing a PR I want to see what you guys think about this -- would it be ok? Is this really "advanced", or possibly the norm?

**Comment by Nevon** [comment]
Intuitively I like this idea, since as you say, there's no real reason that multiple different clients couldn't share connections. One issue I see immediately though is that currently cluster metadata lives on the cluster and is determined by `targetTopics`. This would be different for different consumers. It might be that what you actually want to share is the BrokerPool, which is where the connections live. If that's the layer that's being shared, you could share it between multiple consumers as well as producers or admin clients.

What I don't necessarily like about it is that:

1. It may complicate the code. We don't know that without trying, so I'm not discounting the idea just based on this, but the benefit needs to outweigh the complexity. As long as the complexity doesn't find its way deep inside several layers of the code, it's probably fine.
2. I would be a little worried that people will use this (complicating their code a lot, since you now have a shared lifecycle between multiple consumers) without it actually benefitting them. If your client is talking to 15 brokers, I don't think it will make any difference whether you have 30 connections or 15 from the client's perspective - you still only have <15 cores to pull data from the socket. That said, it may make a difference from the broker perspective. Do you know if any other clients do something similar?

**Comment by ankon** [comment]
> It might be that what you actually want to share is the BrokerPool

I'm also suspecting more that, than the complete `Cluster` instance.

> That said, it may make a difference from the broker perspective. Do you know if any other clients do something similar?

ISTR (very vaguely) that node-rdkafka would share the connections, but this is part of the "need to look into" TODO list :)
Same for the official Kafka client of course, which I'm less familiar with.

And again, yes, there's certainly a complexity question involved (on KafkaJS side, and on the user-of-the-library side), and there is a latency question involved as well: If you try to do high frequency polling, then with more consumers sharing the connection the latency for those polls will go up as well I think. 

My very very very rough guess right now is that I want to try sharing a single set of connections "per tenant" in our application, which would bring down the connections already by a factor of 5-10 (... topics consumed "per tenant").

**Comment by ankon** [comment]
Small update here: I'm testing a fork of KafkaJS right now with this enabled, and initially things look very promising. In particular the number of open connections goes down as expected, but more importantly: The CPU usage of the clients themselves goes down considerably.

Here's an image from our grafana, showing the CPU usage of an idle client:
![image](https://user-images.githubusercontent.com/1210641/100734500-0f6dcb80-33d0-11eb-8d32-64977ea94a14.png)
(Edited with Gimp to show the before/after clearly)

I'm thinking right now that this may be very much related to us using a very low max wait time (100ms).

**Comment by Nevon** [comment]
Those are some really interesting findings, that indeed act as decent motivation for this change. I would also be very interesting to see if there's a corresponding change in the throughput metrics though. Basically, let's make sure we're not reducing CPU usage by causing congestion somewhere else (by making the request queue longer, for example).

**Comment by ankon** [comment]
> Basically, let's make sure we're not reducing CPU usage by causing congestion somewhere else (by making the request queue longer, for example).

As written in https://github.com/tulios/kafkajs/pull/977#issuecomment-754051006: While we didn't make the request queue on the KafkaJS side longer, we did end up on a similar queue on the broker side. The reduced CPU usage is indeed caused by "congestion" in that sense.

As #977 got closed, I'll close this one as well.
